{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%}
{%if $isMobile%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/mdetail.css" />
{%else%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/detail.css" />
{%/if%} 
 <style type="text/css" media="screen">
 
 </style>
{%/block%} 
{%block name="content"%}
 
 
<div class="container main-wrap {%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}">
 {%if isset($post.id)%}  
    {%if $isapp eq 0%}  
      <div class="bg-img" id="bg-img1" style="background-image:url('{%$post.image%}'); " data-webroot="{%$webroot%}" data-stroot="{%$stroot%}" data-image="{%$post.image%}"> 
        <div class="img-mask_book"  style="background-image:url({%$post.image%});"></div> 
        <!-- <img class="img-mask_book" src="{%$post.image%}" alt=""> -->
        <div class="img_book" style="background-image:url({%$post.image%});"></div> 
      {%if empty($href) eq 0 and $isMobile%} 
          <div class="back_mask"></div>
          <div class="back clearfix {%if $isMobile%}ismobile{%/if%}">  
            <a href="{%$href%}" class="link">
              <span class="icon"></span>
               <span class="text">书籍</span>
            </a> 
         </div>
      {%/if%} 
       
    </div> 
    
   {%/if%}   
  <div class="main-content main-content_book">
     {%if $isapp eq 0%}  
    <div class="title-box">
          <div class="title">
            {%if empty($post.title)==0%}{%$post.title%}{%/if%} 
          </div>
          <span class="title-detail">
              {%$post.author%}&nbsp;/&nbsp;{%$post.press%}&nbsp;/&nbsp;&nbsp;{%$post.publish_time%}&nbsp;/&nbsp;&nbsp;ISBN:{%$post.isbn%} 
          </span> 
    </div>
    {%/if%}  
    <div class="main-content-inner book-rich-text{%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}"> 
       {%if empty($post.content_desc)==0%}{%$post.content_desc%}{%/if%}
    </div>
    <!-- <div class="text-from">
       {%if empty($post.from_detail) eq 0%}
            内容来自{%$post.from%}
       {%elseif empty($post.from) eq 0%}
            <a href="{%$post.url%}" target="_blank">内容来自{%$post.from%}，查看原网页</a>
       {%/if%} 
    </div> -->
  </div> 
 {%/if%}  
</div>

{%if $isapp eq 0%}   
    <div class="header-for-mobile {%if $isMobile%}fixed{%/if%}">
      <a href="/download" class="header-for-mobile-download-link">
      <span class="header-for-mobile-btn">下载iOS版</span>
      <img class="header-for-mobile-logo-img" src="{%$feroot%}/common/img/app-logo.png">
      <span class="header-for-mobile-title">途知</span>
      <span class="header-for-mobile-meta">
        了解景点背后的故事
      </span>
      </a>
    </div> 
    {%if $isMobile%}<div class="fixed fixed_blur"></div> {%/if%} 
{%/if%} 

{%/block%}
{%block name="script"%}
<script> 
    require(['topic/detail'], function (main) {
        main.init();
    }); 
</script>
{%/block%}
