{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%}
{%if $isMobile%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/mdetail.css" />
{%else%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/detail.css" />
{%/if%} 
 
{%/block%} 
{%block name="content"%}
{%if $isapp eq 0%}  
  <div class="container">
    <div class="header-for-mobile">
      <a href="/download" class="header-for-mobile-download-link">
      <span class="header-for-mobile-btn">下载iOS版</span>
      <img class="header-for-mobile-logo-img" src="{%$feroot%}/common/img/app-logo.png">
      <span class="header-for-mobile-title">途知</span>
      <span class="header-for-mobile-meta">
        深度旅行：了解景点、城市的历史、人文、科学、地理等知识
      </span>
      </a>
    </div> 
  </div>
{%/if%}  
<div class="container main-wrap content-wrap{%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}"> 
 {%if isset($post.id)%}  
    {%if $isapp eq 0%}  
      <div class="bg-img" id="bg-img" style="background-image:url('{%$feroot%}/common/img/imgloading.png'); " data-webroot="{%$webroot%}" data-stroot="{%$stroot%}" data-image="{%$post.image%}">  
      <div class="title-box">
          <div class="title">
            {%if empty($post.title)==0%}{%$post.title%}{%/if%}
            <span class="title-detail">
              {%$post.author%}&nbsp;/&nbsp;{%$post.press%}&nbsp;/&nbsp;{%$post.publish_time%}&nbsp;/&nbsp;ISBN:{%$post.isbn%} 
            </span> 
          </div>
          
       </div> 
      <div class="img-mask"></div> 
    </div> 
   {%/if%}   
  <div class="main-content">
    <div class="main-content-inner book-rich-text{%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}"> 
       {%if empty($post.content_desc)==0%}{%$post.content_desc%}{%/if%}
    </div>
    <!-- <div class="text-from">
       {%if empty($post.from_detail) eq 0%}
            内容来自{%$post.from%}
       {%elseif empty($post.from) eq 0%}
            <a href="{%$post.url%}" target="_blank">内容来自{%$post.from%}，查看原网页</a>
       {%/if%} 
    </div> -->
  </div>
{%/if%}  
</div>
 

{%/block%}
{%block name="script"%}
<script> 
    require(['topic/detail'], function (main) {
        main.init();
    }); 
</script>
{%/block%}
