{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content"> 
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}话题 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/topic/list">话题列表</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}话题</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/> 
                     <div class="form-group ">
                          <label for="title" class="control-label col-lg-2">当前状态*</label>
                          <label class="control-label col-lg-2" style="text-align: left;">
                               {%$post.statusName%} 
                          </label>
                      </div>
                    {%/if%}
                  	<input type="hidden" name="status" id="status" value="{%if isset($post.status)%}$post.status{%else%}5{%/if%}"/>
                      <div class="form-group ">
                          <label for="title" class="control-label col-lg-2">主标题*</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="title" name="title" minlength="2" type="text" value="{%if isset($post.title)%}{%$post.title%}{%/if%}" ><label for="title" class="error"></label>
                          </div>
                      </div>
                      <div class="form-group ">
                          <label for="subtitle" class="control-label col-lg-2">副标题</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="subtitle" name="subtitle" minlength="2" type="text"  value="{%if isset($post.subtitle)%}{%$post.subtitle%}{%/if%}"><label for="subtitle" class="error"></label>
                          </div>
                      </div>
                       <div class="form-group ">
                          <label for="desc" class="control-label col-lg-2">补充描述</label>
                          <div class="col-lg-5">
                               <textarea class="form-control" id="desc" name="desc" rows="5">{%if isset($post.desc)%}{%$post.desc%}{%/if%}</textarea><label for="desc" class="error"></label>
                          </div>
                      </div>  
                      <div class="form-group ">
                          <label for="sight_name" class="control-label col-lg-2">所属景点*</label>
                          <div class="col-lg-3"> 
                               <input class="form-control" id="sight_name"    type="text"  autocomplete="off"  placeholder="输入后请在下拉框选择"/>
                          </div>
                           <div class="col-lg-3">
                           	 <div class="alert alert-info" role="alert" id="sight_alert">
                                  {%foreach $sightList as $key=>$item%}
                                  <span class="badge badge-sm label-danger" role="badge">   {%$item.name%}
                                    <button type="button" class="close" data-id="{%$item.id%}"><span class="fa fa-remove"></span></button>
                                  </span> 
                                   {%/foreach%}  
                             </div> 
                           </div> 
                           
                      </div>
                      <div class="form-group ">
                          <label for="sight_name" class="control-label col-lg-2">贴标签*</label>
                          <div class="col-lg-5"> 
                               <select multiple="multiple" class="multi-select" id="tags"  >
                                   {%foreach $tagList as $key=>$item%}
                                     <option value="{%$item.id%}" {%if isset($item.selected)%}selected{%/if%} >{%$item.name%}</option>
                                   {%/foreach%} 
                              </select>
                           </div>  
                      </div>
                      <div class="form-group ">
                       <label for="xy" class="control-label col-lg-2">坐标*</label>
                       <div class="col-lg-5">
                           <input  id="x" name="x"  type="hidden" value="{%if isset($post.x)%}{%$post.x%}{%/if%}">
                           <input  id="y" name="y"  type="hidden" value="{%if isset($post.y)%}{%$post.y%}{%/if%}">
                           <input class="form-control" id="xy"  type="text"  readonly="readonly" value="{%if isset($post.x)%}{%$post.x%},{%$post.y%}{%/if%}"><label for="xy" class="error"></label>  
                        </div>
                        <div class="col-lg-5"> 
                       <button type="button"  class="btn btn-success" id="position">
                              <i class="fa fa-map-marker  fa-3x"></i>点我定位</button>
                       </div> 
                      </div>  
                      <div class="form-group"> 
                          <label for="" class="control-label col-lg-2">背景图片</label>
                          <div class="col-md-9">
                              <div class="fileupload fileupload-new" data-provides="fileupload">
                                  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                      <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="">
                                  </div>
                                  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                  </div>
                                  <div id="imageView" class="imageView thumbnail {%if isset($post.image)%}imagedis{%/if%}" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                    {%if !empty($post.image)%} 
                                    <img src="{%$webroot%}/pic/{%$post.image%}.jpg" alt="">
                                    {%/if%}
                                  </div>
                                  <div>
                                   <span class="btn btn-white btn-file">
                                   <span class="fileupload-new"><i class="fa fa-paper-clip"></i> 选择文件</span>
                                   <span class="fileupload-exists"><i class="fa fa-undo"></i> 换一张</span>
                                   <input type="file" class="default" name="file" id="imageBtn" />
                                   <input type="hidden" name="image" id="image" value="{%if isset($post.image)%}{%$post.image%}{%/if%}" />
                                   </span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> 移除</a>
                                    <button id="upload-img" class="btn btn-success fileupload-exists" data-dismiss="fileupload"><i class="fa fa-cloud-upload"></i> 上传</button>
                                  </div>
                              </div> 
                          </div>
                      </div>
                       <div class="form-group ">
                          <label for="from" class="control-label col-lg-2">来源</label>
                          <div class="col-lg-5"> 
                              <select name="from" id="form-from"> 
                                 {%foreach $sourceList as $key=>$item%}
                                     <option value="{%$item.url%}" {%if isset($post.from)  and $item.from eq $item.id%}selected{%/if%}  data-id="{%$item.id%}">{%$item.name%}</option>
                                  {%/foreach%}   
                              </select>
                              <label for="from" class="error"></label>
                          </div>
                      </div>
                      <div class="form-group ">
                          <label for="url" class="control-label col-lg-2">原文链接</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="url" name="url" minlength="2" type="text"  value="{%if isset($post.url)%}{%$post.url%}{%/if%}"><label for="url" class="error"></label>
                          </div>
                      </div>
                      <div class="form-group ">
                          <label for="summernote" class="control-label col-lg-2">正文</label>
                          <div class="col-lg-10">
                              <div id="summernote" >{%if isset($post.content)%}{%$post.content%}{%/if%}</div>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                            {%if !isset($disabled)%} 
                              <button class="btn btn-danger" type="submit" id="">保存</button>
                            {%/if%}
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/topic/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%}
                              
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%} 
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-multi-select/js/jquery.multi-select.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/jquery-multi-select/css/multi-select.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>    
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote-zh-CN.js" type="text/javascript"></script> 
<link href="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.css" rel="stylesheet" type="text/css"/>  

<script src="{%$feroot%}s/admin/topic/edit.js" type="text/javascript"></script> 

 
{%/block%}