{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content"> 
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">创建话题来源</h4>
              </div>
              <div class="modal-body">
                  <form id="source" >
                     <input type="hidden"  id="source-type"/>
                  <div class="form-group source-name" >
                    <label for="source-name" class="control-label">名称:</label>
                    <input type="text" class="form-control" id="source-name">
                  </div>
                  <div class="form-group source-url">
                    <label for="source-url" class="control-label">网址url(不要http 例如：zhihu.com)</label>
                    <input type="text" class="form-control" id="source-url">
                  </div> 
                </form> 
              </div>
              <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              <button type="button" class="btn btn-primary" id="addSource-btn">创建</button>
            </div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  话题筛选器 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/topic/list">话题列表</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">话题筛选器</a>
					</li>
				</ul>
			</div> 
       <div class=" form">
            <form class="cmxform form-horizontal tasi-form" id="Form"  action="http://www.baidu.com/s"  target="_blank">
              <input name='tn' type='hidden' value='baidu' id="Type"/>
               <div class="form-group ">
                    <label for="sight_name" class="control-label col-lg-2">所属景点*</label>
                    <div class="col-lg-3"> 
                      <div class="input-group">
                        <input class="form-control" id="sight_id" name="" type="hidden"/>
                         <input class="form-control" id="sight_name" type="text"  autocomplete="off"  placeholder="输入后请在下拉框选择"/>
                         <span class="input-group-btn">
                          <button class="btn btn-default" type="button" id="clear-sight"><i class="fa fa-remove"></i></button>
                        </span>
                      </div>
                    </div> 
               </div> 
               <div class="form-group ">
                  <label for="form-from" class="control-label col-lg-2">指定搜索源*</label>
                   <div class="col-lg-10" id="div-from"> 
                       <label class="radio-inline">
                        <input type="radio" name="" data-name="form-from" id="" value="weixin" data-id="" data-type="1">微信公众号
                      </label>  
                     {%foreach $sourceList as $key=>$item%} 
                      <label class="radio-inline">
                        <input type="radio" name="" data-name="form-from" id="" value="{%$item.url%}" data-id="{%$item.id%}" data-type="{%$item.type%}" {%if $key eq 0%}checked{%/if%}>{%$item.name%}
                      </label>
                      {%/foreach%}
                      <span class="help-inline">
                          没有想要的来源？<a href="#" class="openSource" data-type="2">创建</a>一个
                      </span> 
                    </div>
               </div>
               <div class="form-group ">
                          <label for="tags" class="control-label col-lg-2">关键词选择(标签)</label>
                          <div class="col-lg-5">  
                               {%foreach $tagList as $key=>$item%} 
                                <label class="checkbox-inline">
                                  <input type="checkbox" id="" data-name="form-tag" value="{%$item.id%}" data-text="{%$item.name%}"/>{%$item.name%}
                                </label>
                               {%/foreach%}  
                           </div> 
                  </div>
                  <div class="form-group" id="form-group-keywords" style="display:none;">
                        <label for="keywords" class="control-label col-lg-2">关键词选择(百科词条)</label>
                          <div class="col-lg-5"> 
                               <select multiple="multiple" class="multi-select" id="keywords">
                                   
                              </select>
                           </div>  
                  </div>
                  <div class="form-group ">
                     <label for="form-engine" class="control-label col-lg-2">搜索关键词</label> 
                        <div class="col-lg-5"> 
                            <div class="input-group">  
                             <input class="form-control" id="query" name="wd" type="text"  autocomplete="off"/> 
                             <span class="input-group-btn">
                              <button class="btn btn-success" type="submit" id="search-btn" data-toggle="tooltip" title="搜索"><i class="fa fa-search"></i>点我搜索</button>
                            </span>
                            </div>
                        </div> 
                  </div>
                  <hr/> 
                   <div class="form-group ">
                        <label for="url" class="control-label col-lg-2">原文链接*</label>
                        <div class="col-lg-5">  
                             <input class="form-control" id="url" type="text" name="" autocomplete="off"  placeholder=""/> 
                        </div>  
                  </div>
                  <div class="form-group" id="weixin-from-input" style="display:none;">
                        <label for="weixin-from" class="control-label col-lg-2">微信公众号名称*</label>
                        <div class="col-lg-3"> 
                        <input class="form-control" id="weixin-from_id" name="" type="hidden"/> 
                            <input class="form-control" id="weixin-from" type="text" name="" autocomplete="off"  placeholder="输入后请在下拉框选择"/> 
                        </div>
                        <div class="col-lg-3">
                          <p class="help-block">
                             没有想要的公众号？<a href="#" class="openSource" data-type="1">创建</a>一个
                          </p>
                        </div>
                  </div>
                  <div class="form-group "> 
                      <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-danger" type="button" id="addTopic-btn">添加并创建话题</button>
                      </div>  
                  </div>
             </form>
       </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%} 
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/jquery-multi-select/js/jquery.multi-select.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/jquery-multi-select/css/multi-select.css" rel="stylesheet" type="text/css"/>
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>   

<script src="{%$feroot%}s/admin/topic/filter.js" type="text/javascript"></script> 

 
{%/block%}