{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content"> 
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  话题筛选器 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/topic/list">话题列表</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">话题筛选器</a>
					</li>
				</ul>
			</div> 
       <div class=" form">
            <form class="cmxform form-horizontal tasi-form" id="Form"  action="http://www.baidu.com/s"  target="_blank">
              <input name='tn' type='hidden' value='baidu' id="Type"/>
               <div class="form-group ">
                    <label for="sight_name" class="control-label col-lg-2">所属景点*</label>
                    <div class="col-lg-3"> 
                      <div class="input-group">
                        <input class="form-control" id="sight_id" name="" type="hidden"/>
                         <input class="form-control" id="sight_name" type="text"  autocomplete="off"  placeholder="输入后请在下拉框选择"/>
                         <span class="input-group-btn">
                          <button class="btn btn-default" type="button" id="clear-sight"><i class="fa fa-remove"></i></button>
                        </span>
                      </div>
                    </div> 
               </div> 
               <div class="form-group ">
                  <label for="form-from" class="control-label col-lg-2">指定搜索源*</label>
                   <div class="col-lg-3"> 
                        <div class="input-group">
                            <select name="" id="form-from"> 
                                 {%foreach $sourceList as $key=>$item%}
                                     <option value="{%$item.url%}" {%if $item.name eq '知乎'%}selected{%/if%}  data-id="{%$item.id%}">{%$item.name%}</option>
                                  {%/foreach%}   
                            </select>
                        </div>
                    </div>
               </div>
               <div class="form-group ">
                          <label for="tags" class="control-label col-lg-2">关键词选择(标签)</label>
                          <div class="col-lg-5"> 
                               <select multiple="multiple" class="multi-select" id="tags"  >
                                   {%foreach $tagList as $key=>$item%}
                                     <option value="{%$item.id%}" {%if isset($item.selected)%}selected{%/if%} >{%$item.name%}</option>
                                   {%/foreach%} 
                              </select>
                           </div> 
                  </div>
                  <div class="form-group" id="form-group-keywords" style="display:none;">
                        <label for="keywords" class="control-label col-lg-2">关键词选择(百科词条)</label>
                          <div class="col-lg-5"> 
                               <select multiple="multiple" class="multi-select" id="keywords">
                                   
                              </select>
                           </div>  
                  </div>
                  <div class="form-group ">
                     <label for="form-engine" class="control-label col-lg-2">搜索关键词</label>
                      <!--   <div class="col-lg-1"> 
                          <div class="input-group">
                              <select name="" id="form-engine"> 
                                <option value="http://www.baidu.com">百度</option> 
                                <option value="http://weixin.sogou.com/weixin">搜狗</option>  
                              </select>
                          </div>
                      </div>  -->
                        <div class="col-lg-5"> 
                            <div class="input-group">  
                             <input class="form-control" id="query" name="wd" type="text"  autocomplete="off"/> 
                             <span class="input-group-btn">
                              <button class="btn btn-default" type="submit" id="search-btn" data-toggle="tooltip" title="搜索"><i class="fa fa-search"></i></button>
                            </span>
                            </div>
                        </div> 
                  </div>
                   <div class="form-group "> 
                      <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-danger" type="submit" id="search-btn2">点我搜索</button>
                      </div>  
                  </div>
                   <div class="form-group ">
                        <label for="url" class="control-label col-lg-2">原文链接*</label>
                          <div class="col-lg-5">  
                             <input class="form-control" id="url" type="text" name="" autocomplete="off"  placeholder=""/> 
                           </div>  
                  </div>
                  <div class="form-group "> 
                      <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-danger" type="button" id="addTopic-btn">添加并创建话题</button>
                      </div>  
                  </div>
             </form>
       </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%} 
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/jquery-multi-select/js/jquery.multi-select.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/jquery-multi-select/css/multi-select.css" rel="stylesheet" type="text/css"/>
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>   

<script src="{%$feroot%}s/admin/topic/filter.js" type="text/javascript"></script> 

 
{%/block%}