<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"> 
    {%if $isMobile%}  
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta content="black" name="apple-mobile-web-app-status-bar-style" />
    <meta name="format-detection" content="telephone=no, email=no">
    {%/if%}
    
    <title>
         {%if $title%}
         {%$title%}
         {%else%}  
              途知          
         {%/if%} 
    </title>
    <!--[if lt IE 7]>
    <script>
        // window.location.href = '{%$webroot%}/static/ieup/index.html';
    </script>
    <![endif]-->
    <link rel="icon" href="{%$webroot%}/favicon.ico" type="image/x-icon" />

    <script src="{%$feroot%}/common/extra/esl.js"></script>

    <script>
        require.config({
            'baseUrl': '{%$feroot%}',
            'paths': {
            },
            'packages': [
               /* {
                    'name': 'echarts',
                    'location': '../dep/echarts/2.1.9/asset',
                    'main': 'echarts'
                },
                {
                    'name': 'est',
                    'location': '../dep/est/1.3.0/asset'
                },
                {
                    'name': 'etpl',
                    'location': '../dep/etpl/3.0.0/asset',
                    'main': 'main'
                },
                {
                    'name': 'jquery',
                    'location': '../dep/jquery/1.9.1/asset',
                    'main': 'jquery.min'
                },
                {
                    'name': 'moment',
                    'location': '../dep/moment/2.7.0/asset',
                    'main': 'moment'
                },
                {
                    'name': 'saber-emitter',
                    'location': '../dep/saber-emitter/1.0.0/asset',
                    'main': 'emitter'
                },
                {
                    'name': 'zrender',
                    'location': '../dep/zrender/2.0.6/asset',
                    'main': 'zrender'
                } */
            ]
        });

 
    </script>
