<!--  <nav class="lincoapp-nav  h_tab_head">   
   <div class="h_nav_inner nav">            
     <div class="h_tab_scroll scroll">           
       <div class="h_tab_inner">           
         <li class="{%if $selected == 'guide'%}selected{%/if%}" >
           <a href="/m/sight/guide?id={%$sightId%}">导游</a>
         </li>
         <li class="{%if $selected == 'food'%}selected{%/if%}" >
           <a href="/m/sight/foodlist?id={%$sightId%}">美食</a>
         </li>
         <li class="{%if $selected == 'specialty'%}selected{%/if%}" >
           <a href="/m/sight/specialtylist?id={%$sightId%}">特产</a>
         </li>
         <li class="{%if $selected == 'specialty'%}selected{%/if%}" >
           <a href="/m/sight/specialtylist?id={%$sightId%}">特产2</a>
         </li> 
         <li class="{%if $selected == 'specialty'%}selected{%/if%}" >
           <a href="/m/sight/specialtylist?id={%$sightId%}">特产3</a>
         </li> 
         <li class="{%if $selected == 'specialty'%}selected{%/if%}" >
           <a href="/m/sight/specialtylist?id={%$sightId%}">特产4</a>
         </li>           
       </div>       
     </div>   
   </div>   
  </nav> -->
 
 
<div id="nav">
  <div class="scroller">
    <ul>
       <!-- <li class="{%if $selected == 'guide'%}selected{%/if%}" >
                 <a href="/m/sight/guide?id={%$sightId%}">导游</a>
               </li>
               <li class="{%if $selected == 'food'%}selected{%/if%}" >
                 <a href="/m/sight/foodlist?id={%$sightId%}">美食</a>
               </li>
               <li class="{%if $selected == 'specialty'%}selected{%/if%}" >
                 <a href="/m/sight/specialtylist?id={%$sightId%}">特产</a>
               </li>  -->        
    </ul>
  </div>
</div>
 