{%if $smarty.const.MODULE eq 'Index'%}
	{%include file='common/header.phtml'%}
{%else%}
	{%include file='../../../views/common/header.phtml'%}
{%/if%}

</head>
<body class="page">

    <div id="main-wraper">
        {%block name="content"%}{%/block%}
    </div>

    {%if $smarty.const.MODULE eq 'Index'%}
		{%include file='common/footer.phtml'%}
	{%else%}
		{%include file='../../../views/common/footer.phtml'%}
	{%/if%}
	
    {%block name="link"%}{%/block%}
    {%block name="script"%}{%/block%}
    