{%extends file='common/layout.phtml'%}
{%block name='content'%} 
  <div class="page-content-wrapper">
    <div class="page-content">
      <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->  
      <!-- /.modal -->
      <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <!-- BEGIN PAGE HEADER-->
      <h3 class="page-title">
        {%$action%}后台用户 <small>reports & statistics</small>
      </h3>
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <i class="fa fa-home"></i>
            <a href="/admin">Home</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <i class="fa fa-list-ul"></i>
            <a href="/admin/adminuser/list">后台用户管理</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="#">{%$action%}后台用户</a>
          </li>
        </ul>
      </div>
      <!-- END PAGE HEADER-->
      <!-- BEGIN content STATS --> 
         <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/>
                    {%/if%} 
                      <div class="form-group ">
                          <label for="name" class="control-label col-lg-2">用户名*</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="name" name="name"  type="text" required="" value="{%if isset($post.name)%}{%$post.name%}{%/if%}"/>
                              <label for="name" class="error"></label> 
                          </div>
                      </div>  
                      <div class="form-group ">
                          <label for="role" class="control-label col-lg-2">角色*</label>
                          <div class="col-lg-5">
                              <select name="role" id="form-role">  
                               {%foreach $roleArray as $key=>$item%} 
                                    <option value="{%$key%}" {%if isset($post.role) and $post.role eq $key%}selected{%/if%}>{%$item%}</option> 
                               {%/foreach%}  
                              </select> 
                               <label for="role" class="error"></label>
                          </div> 
                      </div>  
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                              {%if !isset($disabled)%} 
                                <button class="btn btn-danger" type="submit" id="" >保存</button> 
                              {%/if%} 
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/adminuser/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%} 
                          </div>
                      </div>
                  </form>
              </div>
      <!-- END content STATS -->
    </div>
  </div>

{%/block%}
{%block name='link'%}   
 <link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
{%/block%}
{%block name='script'%}   
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/adminuser/edit.js" type="text/javascript"></script>  

 
{%/block%}