{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content"> 
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  标签关系管理 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/tag">标签列表 </a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">标签关系管理 </a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="/admin/tagapi/saveRelation" novalidate="novalidate"  onsubmit="">                                             
                       <div class="form-group ">
                         <label for="tag_first" class="control-label col-lg-2">一级标签列表：</label>
                          <div class="col-lg-10">  
                              {%foreach $data_first as $key=>$item%}
                              <label class="radio-inline">
                              {%if $item.checked ==true%}
                                <input type=radio name="firstid" data-name="firstid" id="first" value="{%$item.id%}"  onclick="change({%$item.id%})" checked>{%$item.name%}                                
                              {%else%}
                                <input type=radio name="firstid" data-name="firstid" id="first" value="{%$item.id%}"  onclick="change({%$item.id%})">{%$item.name%}
                               {%/if%}
                              </label>
                              {%/foreach%}                                                             
                           </div> 
                           
                          <label for="tag_second" class="control-label col-lg-2">二级标签列表：</label>
                          <div class="col-lg-10"> 
                             {%foreach $data_second as $key=>$val%}
                               <label class="checkbox-inline">
                                 {%if $val.checked == true%}
                                   <input type=checkbox name="secondid[]" data-name="secondid" value="{%$val.id%}" checked>{%$val.name%}
                                  {%else%}
                                   <input type=checkbox name="secondid[]" data-name="secondid"  value="{%$val.id%}">{%$val.name%}
                                   {%/if%}
                              </label>
                              {%/foreach%}
                                                                                             
                           </div>                            
                      </div> 
                      
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-danger" type="submit" data-action="send">保存</button>
                               <!--  <button class="btn btn-danger" type="submit" id="" data-status="2">定时发送</button> -->
                                <a class="btn btn-default"  href="/admin/tag">返回列表</a>  
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/tag/edit.js" type="text/javascript"></script> 

 
{%/block%}