{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Modal title</h4>
						</div>
						<div class="modal-body">
							 Widget settings form goes here
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Save changes</button>
							<button type="button" class="btn default" data-dismiss="modal">Close</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			标签管理 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">标签管理</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		    <div class="adv-table editable-table ">
		    	<div class="clearfix">
                  <div class="btn-group">
                      <button id="editable-new" class="btn  btn-success">
                          添加 <i class="fa fa-plus"></i>
                      </button>
                  </div> 
                  <!-- <div class="btn-group pull-right">
                      <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                      </button>
                      <ul class="dropdown-menu pull-right">
                          <li><a href="#">Print</a></li>
                          <li><a href="#">Save as PDF</a></li>
                          <li><a href="#">Export to Excel</a></li>
                      </ul>
                  </div> -->
                </div> 
               <!--  <table class="table table-striped table-hover table-bordered dataTable" id="editable" aria-describedby="editable-sample_info" style="width: 1096px;"> -->
               <table class="table table-striped table-hover table-bordered dataTable DTTT_selectable" id="editable">
                     <thead>
                         <tr role="row">  
                         	<th class="">ID</th>
			                <th class="">名称</th>
			                <th class="">类型</th>
			                <th class="">创建时间</th>
			                <th class="">更新时间</th>
			                <th class="">操作</th>  
		                  </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
		     
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%} 
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<!-- <script src="{%$feroot%}s/admin/common.js" type="text/javascript"></script> --> 
<script src="{%$feroot%}s/admin/tag/index.js" type="text/javascript"></script> 

<!--  <link href="{%$feroot%}s/global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">
<script src="{%$feroot%}s/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js"></script> -->

	<script>
  
	</script>
{%/block%}