{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%} 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/sight/css/foodlist.css" /> 
 <style type="text/css" media="screen">
 .item .content-box{
      -moz-box-flex: 1;
    -webkit-box-flex: 1;
    -webkit-flex: 1;
    -moz-flex: 1;
    -ms-flex: 1;
    flex: 1;
 }
 
 </style>
 
  
{%/block%} 
{%block name="content"%}
<!-- <div class="container"> </div> -->
{%include file='../../../views/common/nav.phtml'  selected="food" sightId="{%$sight['id']%}"%}
 

<div class="container" id="wrapper" sightId="{%$sight.id%}" tagId="{%$tagId%}">
  <div id="scroller">
    <div id="pullDown" class="hidden">
       <span class="pullDownIcon"></span>
       <span class="pullDownLabel"></span>
    </div>
    <ul class="food_list" id="food_list">  
       <div class="tuzhi-loading">&nbsp;</div> 
        
       
    </ul>
    <div id="pullUp"  class="hidden">
        <span class="pullUpIcon"></span><span class="pullUpLabel"></span>
    </div>
  </div>
</div>
</div>

{%/block%}
{%block name="script"%}
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script> 
    require(['m/sight/foodlist'], function (main) {
        main.init();
    }); 
</script>
{%/block%}
