{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%} 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/sight/css/guide.css" /> 
 <style type="text/css" media="screen">
 
 
 </style>
 
 
 
 
 
 
{%/block%} 
{%block name="content"%}
 
<div class="container">  
{%include file='../../../views/common/nav.phtml'  selected="guide" sightId="{%$sight['id']%}"%}
   
   
  
</div>
<div class="container" id="wrapper" sightId="{%$sight.id%}" tagId="{%$tagId%}">
  <div id="scroller">
    <div id="pullDown" class="hidden">
       <span class="pullDownIcon"></span>
       <span class="pullDownLabel"></span>
    </div>
    <div class="title-box" style="background-image: url(/pic/{%$sight.image%})">
      <div class="img_mask"></div>
      <div class="name-box">
        <span class="sight_name">{%$sight.name%}</span>
        <!-- <i class="icon_map"></i>
        <a class="tomap">切换地图</a> -->
      </div>
      <div class="desc-box">
         <div class="describe">{%$sight.describe%}</div>
         <div class="radio {%if isset($sight.audio) eq 0 %}hidden{%/if%}" style=" ">
           <div class="time">{%$sight.audio_len%}</div>
         </div>

      </div>
   </div>
    <ul class="landscape_list" id="landscape_list">  
       <div class="tuzhi-loading">&nbsp;</div>  
    </ul>
    <div id="pullUp"  class="hidden">
        <span class="pullUpIcon"></span><span class="pullUpLabel"></span>
    </div>
  </div>
</div>
</div>

{%/block%}
{%block name="script"%}
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script> 
    require(['m/sight/guide'], function (main) {
        main.init();
    }); 
</script>
{%/block%}
