{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%} 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/common/extra/jplayer/jquery.jplayer.css" /> 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/sight/css/landscape.css" /> 
 <style type="text/css" media="screen">
  
 </style> 
 
{%/block%} 
{%block name="content"%} 
<div class="container" id="wrapper">
   <div class="img_bg"  style="background-image: url(/pic/{%$landscape.image%})">
       <div class="img_mask"></div>
       <!-- <div class="name">{%$landscape.name%}</div> -->
       <div class="content">{%$landscape.content%}</div>
       <div class="more">查看更多</div>
       <div id="jPlayerBox"></div>
       <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player"> 
          <div class="jp-type-single">
            <div class="jp-gui jp-interface"> 
              <div class="jp-controls-holder">
                <div class="jp-controls"> 
                  <button class="jp-play" role="button" tabindex="0">播放</button>  
                </div>
                <div class="jp-progress-box">
                   <div class="jp-current-time" role="timer" aria-label="time">&nbsp;2323</div> 
                  <div class="jp-progress"> 
                    <div class="jp-seek-bar">
                      <div class="jp-play-bar"></div>
                    </div>
                    <div class="jp-play-ball"></div> 
                  </div>
                  <div class="jp-duration-time" role="timer" aria-label="duration">{%$landscape.audio_len%}</div>
                  
                </div>
               
              </div>
            </div>
            
            <div class="jp-no-solution">
              <span>需要升级</span>
              请升级浏览器到最新版本或者升级您的 <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash 插件</a>.
            </div>
          </div>
       </div>
   </div> 
</div> 

 
{%/block%}
{%block name="script"%} 
<script> 
    require(['m/sight/landscape'], function (main) {
        main.init('{%if not empty($landscape.audio) eq 1%}{%$landscape.audio%}{%/if%}');
 
    }); 
</script>
{%/block%}
