{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%} 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/common/extra/jplayer/jquery.jplayer.css" /> 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/m/sight/css/landscape.css" /> 
 <style type="text/css" media="screen">
 
 </style> 
 
 
{%/block%} 
{%block name="content"%} 
<div class="container" id="wrapper">
   <div class="img_box ">
       <div class="img_bg blur" style="background-image: url(/pic/{%$post.image%})"></div>
       <div class="img_mask"></div>
       <!-- <div class="name">{%$post.name%}</div> -->
       {%if empty($tagName) eq 0 and $isMobile%}
        <div class="back_mask"></div>
         <div class="back clearfix {%if $isMobile%}ismobile{%/if%}"> 
            <a href="{%$href%}" class="link">
              <span class="icon"></span>
              <span class="text">{%$tagName%}</span>
            </a> 
         </div>
       {%/if%} 
       <div class="content">{%$post.content%}</div>
       <div class="more">查看更多</div>
       {%if empty($post.audio_len)==0%}  
       <div id="jPlayerBox"></div>
       <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player"> 
          <div class="jp-type-single">
            <div class="jp-gui jp-interface"> 
              <div class="jp-controls-holder">
                <div class="jp-controls"> 
                  <button class="jp-play" role="button" tabindex="0">播放</button>  
                </div>
                <div class="jp-progress-box">
                   <div class="jp-current-time" role="timer" aria-label="time">&nbsp;2323</div> 
                  <div class="jp-progress"> 
                    <div class="jp-seek-bar">
                      <div class="jp-play-bar"></div>
                    </div>
                    <div class="jp-play-ball"></div> 
                  </div>
                  <div class="jp-duration-time" role="timer" aria-label="duration">{%$post.audio_len%}</div>
                  
                </div>
               
              </div>
            </div>
            
            <div class="jp-no-solution">
              <span>需要升级</span>
              请升级浏览器到最新版本或者升级您的 <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash 插件</a>.
            </div>
          </div>
       </div>
       {%/if%} 
   </div> 
</div> 

 
{%/block%}
{%block name="script"%} 
<script> 
    require(['m/sight/landscape'], function (main) {
        main.init('{%if not empty($post.audio) eq 1%}{%$post.audio%}{%/if%}');
 
    }); 
</script>
{%/block%}
