{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%} 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/common/extra/jplayer/jquery.jplayer.css" /> 
<link rel="stylesheet" type="text/css" href="{%$feroot%}/keyword/css/map.css" /> 

 <style type="text/css" media="screen">
 #jp_container_1 {
    height: 140pt;

    z-index: 9000;
  }
  .jp-progress-box{
    display: flex;
  }
  .jp-controls {
    display: flex;
    width: 100%;
  }
  .jp-type-playlist .jp-previous{
    flex: 1;
    max-width: 23pt;
  }
  .jp-type-playlist .jp-next{
    flex: 1;
    max-width: 23pt;
  }
  .jp-type-playlist .jp-play{
    flex: 1;
  }
  .jp-audio{
     padding:0pt 53pt 5pt 53pt
  }
 </style>
 
{%/block%} 
{%block name="content"%}
 <div class="container height100"> 
    <div class="mapBox" id="mapBox"> 

    </div> 
    <div id="jPlayerBox"></div>
    <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
      <div class="jp-details">
          <div class="jp-title" aria-label="title">&nbsp;</div>
      </div>
      <div class="jp-type-playlist">
        <div class="jp-gui jp-interface"> 
          <div class="jp-controls-holder">
            <div class="jp-progress-box">
              <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
              <div class="jp-progress"> 
                <div class="jp-seek-bar">
                  <div class="jp-play-bar"></div>
                </div> 
              </div>
              <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
            </div>
            
            <div class="jp-controls">
              <button class="jp-previous" role="button" tabindex="0">上一个</button>
              <button class="jp-play" role="button" tabindex="0">播放</button> 
              <button class="jp-next" role="button" tabindex="0">下一个</button>
            </div>
            
            
            <!-- <div class="jp-toggles">
              <button class="jp-repeat" role="button" tabindex="0">repeat</button>
            </div> -->
          </div>
        </div>
        
        <div class="jp-no-solution">
          <span>Update Required</span>
          To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
        </div>
      </div>
    </div>
 </div>
</div>
 

{%/block%}
{%block name="script"%}
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script> 
    list = {%$list%};
    //center = {lng: {%$sight.x%}, lat: {%$sight.y%}};
    center = [{%$sight.x%},{%$sight.y%}];
    require(['keyword/map'], function (main) {
        main.init(center,list);
    }); 
</script>
{%/block%}
