{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">添加景点词条信息</h4>
						</div>
						<div class="modal-body">
							  
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">保存</button>
							<button type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}景点词条 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/keyword/list">景点词条管理</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}景点词条</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/>
                    {%/if%}
                  	
                      <div class="form-group ">
                          <label for="name" class="control-label col-lg-2">名称*</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="name" name="name"  type="text" required="" value="{%if isset($post.name)%}{%$post.name%}{%/if%}"/>
                              <label for="name" class="error"></label> 
                          </div>
                      </div> 
                      <div class="form-group ">
                          <label for="sight_name" class="control-label col-lg-2">所属景点*</label>
                          <div class="col-lg-5">
                          	   <input  id="sight_id" name="sight_id"  type="hidden" value="{%if isset($post.sight_id)%}{%$post.sight_id%}{%elseif isset($sight)%}{%$sight.id%}{%/if%}">
                               <input class="form-control" id="sight_name" name="sight_name"  type="text" required=""  autocomplete="off" value="{%if isset($post.sight_name)%}{%$post.sight_name%}{%elseif isset($sight)%}{%$sight.name%}{%/if%}"  data-/> 
                               <label for="sight_name" class="error"></label>
                          </div>
                           <div class="col-lg-5">
                           	<p class="help-block">输入后请在下拉框选择(键盘也可选择)，否则无效</p> 
                           </div>
                      </div> 
                      <div class="form-group ">
                          <label for="url" class="control-label col-lg-2">链接url</label>
                          <div class="col-lg-5"> 
                               <input class="form-control" id="url" name="url"  type="text" required="" value="{%if isset($post.url)%}{%$post.url%}{%/if%}"><label for="url" class="error"></label> 
                          </div>
                      </div> 
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                              {%if !isset($disabled)%} 
                                <button class="btn btn-danger" type="submit" id="">保存</button>
                              {%/if%} 
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/keyword/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%}
                              
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/keyword/edit.js" type="text/javascript"></script> 

 
{%/block%}