{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM--> 
        {%include file='utils/map.phtml'%}
        {%include file='utils/corpimg.phtml'%}
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}景观 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/keyword/list">景观管理</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}景观</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/>
                    {%/if%}
                    <input type="hidden" name="status" id="status" value="{%if isset($post.status)%}{%$post.status%}{%/if%}"/>
                  	
                      <div class="form-group ">
                          <label for="name" class="control-label col-lg-2">名称*</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="name" name="name"  type="text" required="" value="{%if isset($post.name)%}{%$post.name%}{%/if%}"/>
                              <label for="name" class="error"></label> 
                          </div>
                      </div> 
                        <div class="form-group ">
                          <label for="xy" class="control-label col-lg-2">坐标*</label>
                          <div class="col-lg-5">
                              <input  id="x" name="x"  type="hidden" value="{%if isset($post.x)%}{%$post.x%}{%/if%}">
                              <input  id="y" name="y"  type="hidden" value="{%if isset($post.y)%}{%$post.y%}{%/if%}">
                              <input class="form-control disabled" id="xy"  type="text" readonly="readonly" required="" value="{%if isset($post.x)%}{%$post.x%},{%$post.y%}{%/if%}"><label for="xy" class="error"></label>  
                           </div>
                           <div class="col-lg-5"> 
                          <button type="button"  class="btn btn-success" id="position">
                               	<i class="fa fa-map-marker  fa-3x"></i>点我定位</button>
                          </div> 
                      </div>
                      <div class="form-group ">
                          <label for="sight_name" class="control-label col-lg-2">所属景点*</label>
                          <div class="col-lg-5">
                          	   <input  id="sight_id" name="sight_id"  type="hidden" value="{%if isset($post.sight_id)%}{%$post.sight_id%}{%elseif isset($sight)%}{%$sight.id%}{%/if%}">
                               <input class="form-control" id="sight_name" name="sight_name"  type="text" required=""  autocomplete="off" value="{%if isset($post.sight_name)%}{%$post.sight_name%}{%elseif isset($sight)%}{%$sight.name%}{%/if%}"  data-/> 
                               <label for="sight_name" class="error"></label>
                          </div>
                           <div class="col-lg-5">
                           	<p class="help-block">输入后请在下拉框选择(键盘也可选择)，否则无效</p> 
                           </div>
                      </div> 
                    <div class="form-group ">
                       <label for="url" class="control-label col-lg-2">链接url</label>
                       <div class="col-lg-4">  
                            <input class="form-control" type="text" name="url" id="url" value="{%if isset($post.url)%}{%$post.url%}{%/if%}" />
                             <p class="help-inline">url状态：{%if isset($post.status_name)%}{%$post.status_name%}{%/if%}</p> 
                            <label for="url" class="error"></label> 
                       </div> 
                        <div class="col-lg-1">

                            <a class="btn btn-default" target="_blank" id="view-link" href="{%if isset($post.url)%}{%$post.url%}{%/if%}">查看</a> 
                       </div>
                   </div>  
                   
                   <div class="form-group ">
                          <label for="content" class="control-label col-lg-2">简介*</label>
                          <div class="col-lg-9">
                            <textarea  class="form-control" type="text" name="content" id="content" rows=5 >{%if isset($post.content)%}{%$post.content%}{%/if%}</textarea>                             
                          </div>
                   </div> 
                   
                   <div class="form-group"> 
                          <label for="" class="control-label col-lg-2">图片</label>
                          <div class="col-md-9">
                              <div class="fileupload fileupload-new" data-provides="fileupload">
                                  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                      <img src="{%$feroot%}s/global/img/no_image.png" alt="">
                                  </div>
                                  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                  </div>
                                  <div id="imageView" class="imageView thumbnail {%if isset($post.image)%}imagedis{%/if%}" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                    {%if empty($post.image) eq 0%}  
                                     <img src="{%$webroot%}/pic/{%$post.image%}@f190w_f80h" alt=""> 
                                    {%/if%}
                                  </div> 
                                    <button id="crop-img" class="btn btn-primary fileupload-crop{%if empty($post.image)==1%} hidden{%/if%}" type="button" data-corpUrl="sight"><i class="fa fa-cut"></i>裁剪</button>
                                    <input type="hidden" id="jcrop-ratio" data-width="414" data-height="166"/>
                                  <div>
                                   <span class="btn btn-white btn-file">
                                   <span class="fileupload-new"><i class="fa fa-paper-clip"></i> 选择文件</span>
                                   <span class="fileupload-exists"><i class="fa fa-undo"></i> 换一张</span>
                                   <input type="file" class="default" name="file" id="imageBtn" />
                                   <input type="hidden" name="image" id="image" value="{%if isset($post.image)%}{%$post.image%}{%/if%}" />
                                   </span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> 移除</a>
                                    <button id="upload-img" class="btn btn-success fileupload-exists" data-dismiss="fileupload"><i class="fa fa-cloud-upload"></i> 上传</button>
                                  </div>
                              </div> 
                          </div>
                      </div>
                      
                     <input class="form-control" id="audio_len" name="audio_len"  type="hidden" required="" value=""/>
                      
                      <div class="form-group"> 
                          <label for="" class="control-label col-lg-2">音频</label>
                          <div class="col-md-9">
                              <div style="float:left;width:30%;"><label class="control-label col-lg-2" id="label_audio">{%if isset($post.audio)%}{%$post.audio%}{%/if%}</label> </div>
                              <div style="float:left;width:30%;"><input type="file" name="file" id="audioupload"/> </div>
                              
                              <input type="hidden" name="audio" id="audio" value="{%if isset($post.audio)%}{%$post.audio%}{%/if%}" />                        
                          </div>
                      </div>
                      
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                              {%if !isset($disabled)%} 
                                <button class="btn btn-danger" type="submit" id="" data-status="1">只保存</button>
                                <button class="btn btn-danger" type="submit" id="" data-status="2">确认并保存</button>
                              {%/if%} 
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/keyword/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%} 
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='link'%}
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/> 
{%/block%}
{%block name='script'%}  
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script>
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script>    
<script src="{%$feroot%}s/admin/keyword/edit.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/utils/map/index.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/utils/cropimg/index.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/jcrop/js/jquery.Jcrop.js" type="text/javascript"></script>
{%/block%}