{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->      
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              景观推荐 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">景观推荐</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS -->              
            <div class="adv-table editable-table ">
                 <div class="clearfix">                                        
                    <div class="col-xs-2 pull-right">   
                        <div class="input-group ">
                          <select name="" id="form-status">  
                             {%foreach $statusTypeArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                             {%/foreach%}  
                          </select>
                       </div>
                  </div>
                  
                    <div class="col-xs-3 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入并选择城市" aria-describedby="sightName" id="form-city" autocomplete="off" value="{%if isset($sight)%}{%$sight.name%}{%/if%}" data-sight_id="{%if isset($sight)%}{%$sight.id%}{%/if%}"/>
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-city"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                    </div> 
                </div>  
                 
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                            <th rowspan="2" class="mainth">ID</th> 
                            <th rowspan="2" class="mainth">景观名称</th> 
                            <th rowspan="2" class="mainth">城市</th>  
                            <th colspan="3">
                              推荐结果
                                <span class="label">推荐结果</span>
                            </th>
                          </tr>
                          <tr role="row"> 
                              <th>推荐景点</th> 
                              <th>景点城市</th> 
                              <th>状态</th>    
                              <th>操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='link'%}  
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
 <link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
 <style type="text/css" media="screen">
   .table-scrollable > .table-bordered > tbody > tr.group > td:last-child{
    border-right: 1px solid #ddd;;
   }
 </style> 
{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>

<script src="{%$feroot%}s/admin/keyword/recommend.js" type="text/javascript"></script> 
 
{%/block%}