{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">添加书籍信息</h4>
						</div>
						<div class="modal-body">
							  
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">保存</button>
							<button type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
       {%include file='utils/corpimg.phtml'%}
        {%include file='utils/map.phtml'%}
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}书籍 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/book/list">书籍管理</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}书籍</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		  <div class="form">
          <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
              {%if isset($post.id)%}
                <input type="hidden" name="id" id="id" value="{%$post.id%}"/>
                <div class="form-group ">
                      <label for="title" class="control-label col-lg-2">当前状态：</label>
                      <label class="control-label col-lg-3" style="text-align: left;">
                        {%$post.statusName%} 
                      </label>
                       <label for="guid" class="control-label col-lg-1">ISBN：</label>
                    <label class="control-label col-lg-2" style="text-align: left;">
                        {%if isset($post.isbn)%}{%$post.isbn%}{%/if%}
                    </label>
                </div>
              {%else%}
                   <!-- <a href="javascript:window.close()" id="closeWin">关闭窗口</a> -->
                     <script type="text/javascript"> 
                   alert('参数错误，如果想添加书籍去列表页的【书籍添加器】吧。'); 
                   //$('#closeWin').click();
                      </script>  
              {%/if%}  
              <div class="form-group ">
                  <label for="title" class="control-label col-lg-2">书籍名称*：</label>
                  <div class="col-lg-7">
                      <input class="form-control" id="title" name="title"  type="text"  value="{%if isset($post.title)%}{%$post.title%}{%/if%}"><label for="title" class="error"></label>
                  </div>
              </div>
              <div class="form-group ">
                  <label for="author" class="control-label col-lg-2">作者：</label>
                  <div class="col-lg-3">
                      <input class="form-control" id="author" name="author"  type="text"  value="{%if isset($post.author)%}{%$post.author%}{%/if%}"><label for="author" class="error"></label>
                  </div>

                  <label for="press" class="control-label col-lg-1">出版社：</label>
                  <div class="col-lg-3">
                      <input class="form-control" id="press" name="press"  type="text"  value="{%if isset($post.press)%}{%$post.press%}{%/if%}"><label for="press" class="error"></label>
                  </div>
              </div> 
              <div class="form-group ">
                  <label for="url" class="control-label col-lg-2">链接：</label>
                  <div class="col-lg-4">
                      <input class="form-control" id="url" name="url"  type="text"  value="{%if isset($post.url)%}{%$post.url%}{%/if%}"><label for="url" class="error"></label>
                  </div>
                  <div class="col-lg-1"> 
                      <a class="btn btn-default" target="_blank" id="view-link" href="{%if isset($post.url)%}{%$post.url%}{%/if%}">查看</a> 
                  </div>
              </div>
              <div class="form-group ">
                  <label for="publish_time" class="control-label col-lg-2">出版时间：</label>
                  <div class="col-lg-3"> 
                      <div data-date-viewmode="years" data-date-format="yyyy-mm-dd"   class="input-group input-append date dpYears">
                          <input type="text" readonly="" id="publish_time" name="publish_time" size="16" class="form-control" value="{%if isset($post.publish_time)%}{%$post.publish_time%}{%/if%}">
                          <span class="input-group-btn">
                            <button class="btn btn-danger" type="button"><i class="fa fa-calendar"></i></button>
                          </span>
                      </div>
                      <label for="publish_time" class="error"></label>
                  </div>

                  <label for="pages" class="control-label col-lg-1">页码：</label>
                  <div class="col-lg-3">
                      <input class="form-control" id="pages" name="pages"  type="text"  value="{%if isset($post.pages)%}{%$post.pages%}{%/if%}"><label for="pages" class="error"></label>
                  </div>
              </div> 
              <div class="form-group ">
                  <label for="price_jd" class="control-label col-lg-2">京东价：</label>
                  <div class="col-lg-3">
                      <input class="form-control" id="price_jd" name="price_jd"  type="text"  value="{%if isset($post.price_jd)%}{%$post.price_jd%}{%/if%}"><label for="price_jd" class="error"></label>
                  </div>
                  <label for="price_mart" class="control-label col-lg-1">市场价：</label>
                  <div class="col-lg-3">
                      <input class="form-control" id="price_mart" name="price_mart"  type="text"  value="{%if isset($post.price_mart)%}{%$post.price_mart%}{%/if%}"><label for="price_mart" class="error"></label>
                  </div>
              </div>  
              <div class="form-group">
                <label for="sight_id" class="control-label col-lg-2">景点：</label>
                 <div class="col-lg-3 sight_tag" data-type="sight"> 
                     <input class="form-control" id="sight_name" type="text"  autocomplete="off"  placeholder="输入景点后请在下拉框选择"/>
                </div>
                 <div class="col-lg-3 sight_tag"  data-type="sight">
                   <div class="alert alert-info" role="alert" id="sight_alert">
                        {%foreach $sightList as $key=>$item%}
                        <span class="badge badge-sm label-danger" role="badge">   {%$item.name%}
                          <button type="button" class="close" data-id="{%$item.id%}"><span class="fa fa-remove"></span></button>
                        </span> 
                         {%/foreach%}  
                   </div> 
                 </div>
              </div>
              <div class="form-group"> 
                  <label for="" class="control-label col-lg-2">图片</label>
                  <div class="col-md-9">
                      <div class="fileupload fileupload-new" data-provides="fileupload">
                          <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                              <img src="{%$feroot%}s/global/img/no_image.png" alt="">
                          </div>
                          <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                          </div>
                          <div id="imageView" class="imageView thumbnail {%if isset($post.image)%}imagedis{%/if%}" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                            {%if empty($post.image) eq 0%}  
                             <img src="{%$webroot%}/pic/{%$post.image%}@f190w_f80h" alt=""> 
                            {%/if%}
                          </div> 
                            <button id="crop-img" class="btn btn-primary fileupload-crop{%if empty($post.image)==1%} hidden{%/if%}" type="button" data-corpUrl="book"><i class="fa fa-cut"></i>裁剪</button>
                            <input type="hidden" id="jcrop-ratio" data-width="133" data-height="93"/>
                          <div>
                           <span class="btn btn-white btn-file">
                           <span class="fileupload-new"><i class="fa fa-paper-clip"></i> 选择文件</span>
                           <span class="fileupload-exists"><i class="fa fa-undo"></i> 换一张</span>
                           <input type="file" class="default" name="file" id="imageBtn" />
                           <input type="hidden" name="image" id="image" value="{%if isset($post.image)%}{%$post.image%}{%/if%}" />
                           </span>
                            <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> 移除</a>
                            <button id="upload-img" class="btn btn-success fileupload-exists" data-dismiss="fileupload"><i class="fa fa-cloud-upload"></i> 上传</button>
                          </div>
                      </div> 
                  </div>
              </div> 
              <div class="form-group ">
                  <label for="content_desc" class="control-label col-lg-2">内容摘要：</label>
                  <div class="col-lg-4">
                     <div id="summernote_content_desc" ></div>
                       <!-- <textarea class="form-control" id="content_desc" name="content_desc" rows="3" >{%if isset($post.content_desc)%}{%$post.content_desc%}{%/if%}</textarea> -->
                       <label for="content_desc" class="error"></label>
                  </div>

                   <label for="catalog" class="control-label col-lg-1">目录：</label>
                  <div class="col-lg-4">
                    <div id="summernote_catalog" ></div>
                       <!-- <textarea class="form-control" id="catalog" name="catalog" rows="3" >{%if isset($post.catalog)%}{%$post.catalog%}{%/if%}</textarea>
                       <label for="catalog" class="error"></label> -->
                  </div>  
              </div>
               {%if isset($post.id)%}  
              <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                      {%if !isset($disabled)%} 
                       <button class="btn btn-danger" type="submit" id="submitBtn" data-action="NOTPUBLISHED" data-btn_text="保存">保存</button>
                       <button class="btn btn-danger" type="submit" data-action="PUBLISHED" data-btn_text="发布">发布</button>
                      {%/if%}
                       {%if isset($post.id)%} 
                         <a class="btn btn-default"  href="/admin/book/list">返回列表</a> 
                        {%else%}
                        <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                        {%/if%}
                      
                  </div>
              </div>
              {%/if%}
          </form>
      </div>
			<!-- END content STATS -->
		</div>
	</div>
<div id="content_desc-text" style="display:none;"> 
  {%if isset($post.content_desc)%}
  {%$post.content_desc%} 
  {%/if%} 
</div>
<div id="catalog-text" style="display:none;"> 
  {%if isset($post.catalog)%}
  {%$post.catalog%} 
  {%/if%} 
</div>
{%/block%}
{%block name='link'%}
<link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/> 
<link href="{%$feroot%}s/global/plugins/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.css" rel="stylesheet" type="text/css"/>   
{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>   
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote-zh-CN.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jcrop/js/jquery.Jcrop.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/book/edit.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/utils/cropimg/index.js" type="text/javascript"></script>  

 
{%/block%}