<div class="modal fade" id="pwdModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="">
  <div class="modal-dialog">
     <div class="modal-content"> 
       <form class="cmxform form-horizontal tasi-form" id="changepwd-form" method="post" action="" novalidate="novalidate" > 
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="exampleModalLabel">修改登录密码</h4>
        </div>
          <div class="modal-body"> 
              <div class="form-group ">
                  <label for="oldpasswd" class="control-label col-lg-3">原密码*</label>
                  <div class="col-lg-7">
                      <input class="form-control" id="oldpasswd" name="oldpasswd"  type="password" required=""/>
                      <label for="oldpasswd" class="error"></label>
                  </div>
              </div>
              <div class="form-group ">
                  <label for="passwd" class="control-label col-lg-3">新密码*</label>
                  <div class="col-lg-7">
                      <input class="form-control" id="passwd" name="passwd"  type="password" required="" />
                      <label for="passwd" class="error"></label>
                  </div>
              </div>
              <div class="form-group ">
                  <label for="passwd2" class="control-label col-lg-3">确认新密码*</label>
                  <div class="col-lg-7">
                      <input class="form-control" id="passwd2" name="passwd2"  type="password" required=""/>
                      <label for="passwd2" class="error"></label>
                  </div>
              </div>       
          </div>
          <div class="modal-footer">
            <button class="btn blue" type="submit" id="btn-changepwd">修改</button> 
             <button type="button" class="btn default" data-dismiss="modal">关闭</button>
          </div>
       <input type="hidden" name="status" id="status" value=""/>
      </form> 
    
  </div> 
 </div>
</div> 
 

 
