<div class="modal fade" id="corpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-lg">
     <div class="modal-content"> 
       <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="gridSystemModalLabel">裁剪图片(会覆盖原有的图片)</h4>
        </div>
        <div class="modal-body">
          <form id="coords" >
              <img src="" id="target" alt="[Jcrop Example]" />
              <div id="preview-pane">
                <div class="preview-container">
                   <div id="jcrop-preview" class="jcrop-preview" >
                      
                   </div>  
                   <!--  <img src="" class="jcrop-preview" id="jcrop-preview" alt="" />  --> 
                </div>
              </div>
              <div class="corp-labels"> 
              <label>X1<input type="text" size="4" id="x1" name="x1" /></label>
              <label>Y1<input type="text" size="4" id="y1" name="y1" /></label>
              <!-- <label>X2<input type="text" size="4" id="x2" name="x2" /></label>
              <label>Y2<input type="text" size="4" id="y2" name="y2" /></label> -->
              <label>W&nbsp;<input type="text" size="4" id="w" name="w" /></label>
              <label>H&nbsp;&nbsp;<input type="text" size="4" id="h" name="h" /></label>
              </div>
          </form> 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          <button type="button" class="btn btn-primary" id="corp-btn">确定</button>
         </div>
      </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

<link href="{%$feroot%}s/global/plugins/jcrop/css/jquery.Jcrop.min.css" rel="stylesheet" type="text/css"/> 
<!-- <script src="{%$feroot%}s/global/plugins/jcrop/js/jquery.Jcrop.min.js" type="text/javascript"></script>  -->
 