<!-- <!doctype html>
<html lang="en">
 <head> 
  <title>坐标拾取工具</title> 
<script src="{%$feroot%}s/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script>
注意：作为插件不需要上面两个js   但是高德的api js 需要在引用该插件的页面添加引用
   
 </head>
 <body>
  </body>
</html> --> 

<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">坐标拾取工具</h4>
</div>
<div class="modal-body"> 
   	 <!--  <div id="divCoordinate" class="" style="top: 249px; left: 576px;"> </div> -->
        <div id="hd" class="barn clearfix">
            <div id="myPageTop">
                <table>
                    <tbody><tr class="tr-radio">
                        <td colSpan="2">
                        	按关键字搜索(注：城市一般定位到人民政府，如果有误差，请自行搜索,或者鼠标选择合适的坐标。)
                        </td> 
                    </tr>
                    <tr class="tr-text">
                    	<td>
                            <input type="hidden"  name="cityName" id="cityName"/>
                            <input type="text" name="search" id="txtSearch" placeholder="请输入关键字进行搜索"> 
                            <button type="button" class="btn btn-default btn-search" >搜索</button> 
                        </td> 
                        <td>
                            <input type="text" id="txtCoordinate" name="coordinate" readonly=""> 
                            <button type="button" class="btn btn-default btn-submit">确定</button> 
                        </td>
                    </tr>
                </tbody></table>
            </div>
        </div>
        <div id="hr"></div>
        <div id="myPage">
	       <div id="map" class="amap-container amap-fade-anim"> </div> 
        </div>
 </div>

<link href="{%$feroot%}s/admin/utils/map/index.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/admin/utils/map/index.js" type="text/javascript"></script> 

 
