
<div class="modal" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="">
  <div class="modal-dialog  modal-lg">
     <div class="modal-content"> 
                 <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">坐标拾取工具</h4>
        </div>
        <div class="modal-body"> 
                <div id="hd" class="barn clearfix">
                    <div id="myPageTop">
                        <table>
                            <tbody> 
                          <tr class="tr-radio">
                              <td colspan="2">
                                按关键字搜索(注：搜不到试着切换城市。)
                                <label  class="hide"><input type="radio" name="searchType" value="keyword" checked="">按关键字搜索</label>
                                <label class="hide"><input type="radio" name="searchType" value="coordinate">按坐标搜索</label>
                                <span id="txtSearchMessage" class="message hide"></span>
                              </td> 
                            </tr>
                        <!--     <tr class="tr-text">
                            <td>
                                所在城市：
                              <input type="text"  name="cityName" id="cityName" placeholder="选择城市"/>
                            </td>
                            <td></td>
                        </tr> -->
                            <tr class="tr-text">
                              <td> 
                                <input name="cityName" id="cityName" type="hidden" value="100000"/>
                                    <input type="text" name="search" id="txtSearch" placeholder="请输入关键字进行搜索"> 
                                    <button type="button" class="btn btn-default btn-search" >搜索</button> 
                                </td> 
                                <td>
                                    <input type="text" id="txtCoordinate" name="coordinate" readonly=""> 
                                    <button type="button" class="btn btn-default btn-submit">确定</button> 
                                </td>
                            </tr>
                        </tbody></table>
                    </div>
                </div>
                <div id="hr"></div>
                <div id="myPage">
                 <div id="map" class="amap-container amap-fade-anim"> </div> 
                 <div id="divCoordinate"> </div>  
                 <div id="citySug">
                  <div id="btnCurrentCity">
                    <span>北京市</span> [<a href="javascript:;" id="btnChangeCity">更换城市</a>]
                  </div>
                  <div id="allCityList" class="hide">
                    <div id="closeCityHolder"><a href="javascript:;" title="关闭"></a>选择城市</div>
                    <div id="allCityListSelect">
                      <div id="tdHotCities"> 
                      </div>
                      <table>
                        <tbody>
                        <tr><td colspan="2">城市列表</td> </tr>
                        </tbody>
                        <tbody id="tbodyAllCities"> 
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                </div>
         </div>
     </div>
    
  </div>

</div> 

  
<!-- <script src="{%$feroot%}s/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> -->
<link href="{%$feroot%}s/admin/utils/map/index.css" rel="stylesheet" type="text/css"/>

 
