{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					 <div class="modal-content"> 
              
            </div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  测试页 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li> 
					<li>
						<a href="#">测试页</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                   
                      <div class="form-group ">
                          <label for="summernote" class="control-label col-lg-2">正文：<br/>(注：若想从服务器删除图片，请选中图片点击删除按钮)</label>
                          <div class="col-lg-10">
                              <div id="summernote" ></div>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                            {%if !isset($disabled)%} 
                              <button class="btn btn-danger" type="submit" data-status="1" id="">保存</button>
                              <button class="btn btn-danger" type="submit" data-status="5" id="">发布</button>
                            {%/if%}
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/topic/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%}
                              
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>
{%if isset($post.content)%}
<div id="content-text" style="display:none;"> 
  {%$post.content%} 
</div>
{%/if%}
{%/block%}
{%block name='script'%}   
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-multi-select/js/jquery.multi-select.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/jquery-multi-select/css/multi-select.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>    
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote-zh-CN.js" type="text/javascript"></script> 
<link href="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.css" rel="stylesheet" type="text/css"/>  

<script src="{%$feroot%}s/admin/topic/edit.js" type="text/javascript"></script> 


  

 
{%/block%}