{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog  modal-lg">
                          <div class="modal-content">
                            <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                              <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                  <h4 class="modal-title">选择热门城市</h4>
                              </div>
                              <div class="modal-body"> 
                                    <div class="form-group " id="add-city-inner">
                                        <label  for="obj_id" class="control-label col-lg-2">选择国内城市：</label>
                                        <div class="col-lg-10">
                                        {%foreach $city_inner as $key => $item%}
                                          <input class="form-control"   name="city_id_inner"  type="checkbox" required="" value={%$item.id%}>{%$item.name%}<label for="obj_id" class="error"></label>
                                        {%/foreach%}                                       
                                        </div>
                                    </div>  
                                    
                                    <div class="form-group " id="add-city-outer">
                                        <label  for="obj_id" class="control-label col-lg-2">选择国外城市：</label>
                                        <div class="col-lg-10">
                                        {%foreach $city_outer as $key => $item%}
                                          <input class="form-control"   name="city_id_outer"  type="checkbox" required="" value={%$item.id%}>{%$item.name%}<label for="obj_id" class="error"></label>
                                        {%/foreach%}                                       
                                        </div>
                                    </div>     
                                    
                                                 
                              </div>
                          
                              <div class="modal-footer">
                                  <button class="btn blue" type="submit" id=""  >保存</button>
                                   <button type="button" class="btn default" data-dismiss="modal">关闭</button>
                              </div>
                               <input type="hidden" name="id" id="id" value=""/>
                               <input type="hidden" name="type" id="type" value=""/>
                               
                              </form> 
                          </div>
                          <!-- /.modal-content -->
                      </div>
                      <!-- /.modal-dialog -->
            </div> 
            {%include file='utils/uploadpic.phtml'%}

            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              热门城市列表 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">热门城市列表</a>
                    </li>
                </ul>
            </div>
            
            <div class="col-xs-1 pull-left">   
                       <div class="input-group">
                          <select name="" id="form-is_china">  
                            <option value="1">国内</option> 
                            <option value="0">国外</option>   
                          </select>
                       </div>
                   </div>
            
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table "> 
                <br>
               <input type="hidden" id="search-id">
                
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row"> 
                            <th>ID</th>
                            <th>城市名</th>
                            <th>创建时间</th>
                            <th>更新时间</th> 
                            <th>操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='script'%} 
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/admin/city/hot.js" type="text/javascript"></script> 
 
{%/block%}