{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM--> 
            <div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div> 
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            城市管理 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">城市管理</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS -->  
            <!--   <form class="form-inline" role="form" action="" >
                <div class="form-group">
                    <label class="sr-only" for="exampleInputEmail2">输入省份</label>
                    <input type="text" class="form-control typeahead" id="form-province" placeholder="输入省份"> 
                </div>  
               <button type="button" class="btn btn-success" id="form-search">搜索</button>
            </form> -->
            <div class="row">
	              <div class="col-xs-3">
	              <div class="input-group input-group">
					  <span class="input-group-addon" id="sizing-addon1">选择省份</span>
					  <input type="text" class="form-control" placeholder="输入省份" aria-describedby="sizing-addon1" id="form-province" autocomplete="off">
				   </div>
				</div>
			</div>
               <table class="table table-striped table-hover table-bordered dataTable " id="editable">
                     <thead>
                         <tr role="row">  
                             <th class="">ID</th>
                            <th class="">省份</th>
                            <th class="">城市</th>
                            <th class="">坐标X</th>
                            <th class="">坐标Y</th>
                            <th class="">操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             <!-- END content STATS --> 
    </div> 
{%/block%}
{%block name='script'%} 
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script>
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/city/index.js" type="text/javascript"></script> 
 

{%/block%}
 