{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM--> 
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div> 
             {%include file='utils/map.phtml'%}
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            城市管理 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">城市管理</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS -->
             <div class="adv-table editable-table">   
                <div class="clearfix">
                  <!--   <div class="col-xs-2 pull-right">   
                        <div class="checkbox"> 
                          <label>
                             <input type="checkbox" id="form-user_id" value="{%$userid%}" checked="">只看我发布的
                            </label>
                       </div> 
                  </div>  -->
                    <div class="col-xs-2 pull-right">   
                        <div class="input-group ">
                          <select name="" id="form-status"> 
                            <option value="">全部状态</option> 
                             {%foreach $statusArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                            {%/foreach%}  
                          </select>
                       </div>
                    </div>  
                    <div class="col-xs-3 pull-right">   
                        <div class="input-group " >
                            <input type="text" class="form-control" placeholder="输入并选择城市" aria-describedby="cityName" id="form-city" autocomplete="off"/>
                            <span class="input-group-btn">
                            <button type="button" class="btn btn-white" id="clear-city"><i class="fa fa-remove"></i></button>
                           </span>
                           </div>
                      </div>
                       <div class="col-xs-3 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入并选择省份" aria-describedby="provinceName" id="form-province" autocomplete="off">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-province"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                      </div>

                    <div class="col-xs-3 pull-right">   
                        <div class="input-group " >
                            <input type="text" class="form-control" placeholder="输入并选择国家" data-type="country" id="form-country"  autocomplete="off"/>
                            <span class="input-group-btn">
                            <button type="button" class="btn btn-white" id="clear-country"><i class="fa fa-remove"></i></button>
                           </span>
                           </div>
                      </div>
    			</div>
             </div>
               <table class="table table-striped table-hover table-bordered dataTable " id="editable">
                     <thead>
                         <tr role="row">  
                             <th class="">ID</th>
                            <th class="">大洲</th>
                            <th class="">国家</th>
                            <th class="">省份</th>
                            <th class="">城市</th>
                            <th class="">坐标X</th>
                            <th class="">坐标Y</th>
                            <th>图片</th>
                            <th>
                              相关标签
                              <!-- <span class="label label-success">分类</span> -->
                              <span class="label label-warning">通用</span>
                              <!-- <span class="label label-default">普通</span> -->
                            </th>
                            <th>状态</th>
                            <th class="">操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             <!-- END content STATS --> 
    </div>
    </div> 
{%/block%}

{%block name='link'%} 

 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>
{%/block%}  
{%block name='script'%} 
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script>
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/city/list.js" type="text/javascript"></script>   
<script src="{%$feroot%}s/admin/utils/map/index.js" type="text/javascript"></script>  
 

{%/block%}
 