{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">添加景点信息</h4>
						</div>
						<div class="modal-body">
							  
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">保存</button>
							<button type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
       {%include file='utils/corpimg.phtml'%}
        {%include file='utils/map.phtml'%}
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}景点 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/sight">景点管理</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}景点</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/>
                    {%else%}
                    <div class="alert alert-danger" role="alert">
                      请转至【元数据管理】-【景点元数据】搜索并景点  <a href="/admin/sight/metalist">点击跳转</a>
                    </div>
                     
                    {%/if%}
                  	
                      <div class="form-group ">
                          <label for="name" class="control-label col-lg-2">名称*</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="name" name="name" minlength="2" type="text" required="" value="{%if isset($post.name)%}{%$post.name%}{%/if%}"><label for="name" class="error"></label>
                          </div>
                      </div>
                      <div class="form-group ">
                          <label for="level" class="control-label col-lg-2">级别*</label> 
                          <div class="col-lg-5"> 
                          <select class="form-control" name="level" id="level"> 
							             {%foreach $levelArray as $key=>$item%}
		                          <option value="{%$item%}" {%if isset($post.level) and $item eq $post.level%}selected{%/if%} >{%$item%}</option>
		                       {%/foreach%}
							</select>
							<label for="level" class="error"></label>
						  </div>
                      </div>

                      <div class="form-group ">
                          <label for="describe" class="control-label col-lg-2">描述</label>
                          <div class="col-lg-5">
                               <textarea class="form-control" id="describe" name="describe" rows="3" >{%if isset($post.describe)%}{%$post.describe%}{%/if%}</textarea>
                               <label for="describe" class="error"></label>
                          </div> 
                      </div>
                      <div class="form-group ">
                          <label for="city_name" class="control-label col-lg-2">所属城市*</label>
                          <div class="col-lg-3">
                          	   <input  id="city_id" name="city_id"  type="hidden" value="{%if isset($post.city_id)%}{%$post.city_id%}{%/if%}">
                               <input class="form-control" id="city_name" name="city_name"  type="text" required=""  autocomplete="off" value="{%if isset($post.city_name)%}{%$post.city_name%}{%/if%}"/> 
                               <label for="city_name" class="error"></label>
                          </div>
                           <div class="col-lg-3" id="city_statusName" style="{%if isset($post.city_statusName) eq 0%}display:none{%/if%}">
                             <label class="error">{%$post.city_statusName%}</label> 
                           </div>
                           <div class="col-lg-4">
                           	<p class="help-block">输入后请在下拉框选择(键盘也可选择)，否则无效</p> 
                           </div>
                      </div>
                      <div class="form-group ">
                          <label for="city_name" class="control-label col-lg-2">通用标签：</label>
                          <div class="col-lg-10">  
                              {%foreach $generalTag as $key=>$item%}
                              <label class="checkbox-inline"> 
                                <input type='checkbox' name="" data-name="form-generaltag" id="" value="{%$item.id%}" {%if isset($item.selected)%}checked{%/if%}>{%$item.name%} 
                              </label>
                              {%/foreach%}  
                           </div> 
                      </div>
                       <div class="form-group ">
                          <label for="xy" class="control-label col-lg-2">坐标*</label>
                          <div class="col-lg-5">
                              <input  id="x" name="x"  type="hidden" value="{%if isset($post.x)%}{%$post.x%}{%/if%}">
                              <input  id="y" name="y"  type="hidden" value="{%if isset($post.y)%}{%$post.y%}{%/if%}">
                              <input class="form-control" id="xy"  type="text" required="" readonly="readonly" value="{%if isset($post.name)%}{%$post.x%},{%$post.y%}{%/if%}"><label for="xy" class="error"></label>  
                           </div>
                           <div class="col-lg-5"> 
                          <button type="button"  class="btn btn-success" id="position">
                               	<i class="fa fa-map-marker  fa-3x"></i>点我定位</button>
                          </div> 
                      </div>
                      <div class="form-group"> 
                          <label for="" class="control-label col-lg-2">图片</label>
                          <div class="col-md-9">
                              <div class="fileupload fileupload-new" data-provides="fileupload">
                                  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                      <img src="{%$feroot%}s/global/img/no_image.png" alt="">
                                  </div>
                                  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                  </div>
                                  <div id="imageView" class="imageView thumbnail {%if isset($post.image)%}imagedis{%/if%}" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                    {%if empty($post.image) eq 0%}  
                                     <img src="{%$webroot%}/pic/{%$post.image%}@f190w_f80h" alt=""> 
                                    {%/if%}
                                  </div> 
                                    <button id="crop-img" class="btn btn-primary fileupload-crop{%if empty($post.image)==1%} hidden{%/if%}" type="button" data-corpUrl="sight"><i class="fa fa-cut"></i>裁剪</button>
                                    <input type="hidden" id="jcrop-ratio" data-width="414" data-height="166"/>
                                  <div>
                                   <span class="btn btn-white btn-file">
                                   <span class="fileupload-new"><i class="fa fa-paper-clip"></i> 选择文件</span>
                                   <span class="fileupload-exists"><i class="fa fa-undo"></i> 换一张</span>
                                   <input type="file" class="default" name="file" id="imageBtn" />
                                   <input type="hidden" name="image" id="image" value="{%if isset($post.image)%}{%$post.image%}{%/if%}" />
                                   </span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> 移除</a>
                                    <button id="upload-img" class="btn btn-success fileupload-exists" data-dismiss="fileupload"><i class="fa fa-cloud-upload"></i> 上传</button>
                                  </div>
                              </div> 
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                               <button class="btn btn-danger" type="submit" id="submitBtn" data-action="NOTPUBLISHED" data-btn_text="保存">保存</button>
                               <button class="btn btn-danger" type="submit" data-action="PUBLISHED" data-btn_text="发布">发布</button>
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/sight">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%}
                              
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='link'%}
<link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/> 
{%/block%}
{%block name='script'%} 
<script src="http://webapi.amap.com/maps?v=1.3&key=f102b992de0917e82f23af99e4a69a5e" type="text/javascript" ></script> 
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 
 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
 
<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jcrop/js/jquery.Jcrop.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/sight/edit.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/utils/map/index.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/utils/cropimg/index.js" type="text/javascript"></script> 

 
{%/block%}