{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content">
						 <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">添加景点信息</h4>
						</div>
						<div class="modal-body"> 
							 	<div class="form-group ">
		                          <label for="name" class="control-label col-lg-2">名称*</label>
		                          <div class="col-lg-5">
		                              <input class="form-control" id="name" name="name"  type="text" required="" value=""><label for="name" class="error"></label>
		                          </div>
		                      </div> 
		                      <div class="form-group ">
		                          <label for="url" class="control-label col-lg-2">链接url</label>
		                          <div class="col-lg-5"> 
		                               <input class="form-control" id="url" name="url"  type="text" required="" value=""><label for="url" class="error"></label> 
		                          </div>
		                      </div>  
		                      <div class="form-group ">
		                          <label for="sight_name" class="control-label col-lg-2">所属景点*</label>
		                          <div class="col-lg-5">
		                          	   <input  id="sight_id" name="sight_id"  type="hidden" value="">
		                               <input class="form-control" id="sight_name" name="sight_name"  type="text" disabled="disabled" autocomplete="off" value=""/> 
		                               <label for="sight_name" class="error"></label>
		                          </div>
		                      </div> 
							 
						</div>
						<div class="modal-footer">
							<button type="submit" class="btn blue">保存</button>
							<button type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
						</form> 
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  景点管理 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">景点管理</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		    <div class="adv-table editable-table ">
		    	 <div class="clearfix"> 
                  	 <div class="btn-group">
                      <a  class="btn  btn-success" href="/admin/sight/edit">
                          添加 <i class="fa fa-plus"></i>
                      </a>
                  </div>  
		             <div class="col-xs-3 pull-right">   
		                  	<div class="input-group ">
							  <span class="input-group-addon" id="cityName">按城市搜索</span>
							  <input type="text" class="form-control" placeholder="输入城市" aria-describedby="cityName" id="form-city" autocomplete="off">
						   </div>
					</div>
				</div>  
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                         	<th class="sorting_disabled">ID</th>
                         	<th class="sorting">城市ID</th>
			                <th class="sorting_disabled">名称</th>
			                <th class="sorting">所属城市</th>
			                <th class="sorting">等级</th>
			                <th class="sorting">坐标X</th>
			                <th class="sorting">坐标Y</th>
			                <th class="sorting_disabled">操作</th>  
		                  </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
		     
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%} 
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/sight/index.js" type="text/javascript"></script> 
 
{%/block%}