{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                         
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <div class="modal fade" id="generalTagModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    
                      <div class="modal-content">
                      <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                          <h4 class="modal-title">添加通用标签</h4>
                        </div>
                        <div class="modal-body"> 
                          <div class="form-group ">
                              <label for="name" class="control-label col-lg-2">通用标签:</label>
                              <div class="col-lg-5" id="generalTag-checkbox">
                                   
                              </div>
                          </div>    
                      </div>
                      <div class="modal-footer">
                        <button class="btn blue" type="submit" id="" data-status="1">保存</button> 
                         <button type="button" class="btn default" data-dismiss="modal">关闭</button>
                      </div>
                       <input type="hidden" name="id" id="sight-id" value=""/>
                       <input type="hidden" name="status" id="sight-status" value=""/>
                      </form> 
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              景点元数据 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">景点元数据</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
                 <div class="clearfix"> 
                  <div class="col-xs-2 pull-right">   
                       <div class="input-group ">
                          <select name="" id="form-is_china"> 
                            <option value="1">国内</option> 
                            <option value="0">国外</option>   
                          </select>
                       </div>
                   </div>
                      <div class="col-xs-2 pull-right">   
                        <div class="input-group ">
                          <select name="" id="form-status"> 
                            <option value="">全部状态</option> 
                             {%foreach $statusArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                            {%/foreach%}  
                          </select>
                       </div>
                    </div>   
                    <div class="col-xs-2  pull-right">
                        <div class="input-group " >  
                            <input type="text" class="form-control" id="form-type" placeholder="输入类型点回车">
                            <span class="input-group-btn"> 
                            <button id="from_detail-help" type="button"   data-toggle="popover" class="btn btn-xs btn-warning fa fa-eyedropper" style="margin-left: 4px;" title="可选类型：" data-toggle="tooltip"></button> 
                          </span>
                        </div> 
                    </div>  
                    <div class="col-xs-2  pull-right"> 
                            <input type="text" class="form-control" id="form-city" placeholder="输入城市点回车"> 
                    </div>
                     <div class="col-xs-2  pull-right"> 
                            <input type="text" class="form-control" id="form-province" placeholder="输入省份点回车"> 
                    </div> 
                    <div class="col-xs-2  pull-right">
                            <input type="text" class="form-control" id="form-name" placeholder="输入名称点回车">
                    </div>   
                </div>  
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                            <th>景点ID</th> 
                            <th>名称</th>
                            <th>级别</th>
                            <th>类型</th>
                            <th>大洲</th>
                            <th>国家</th>
                            <th>省份</th>
                            <th>城市</th>
                            <th>图片</th>
                            <th>坐标</th> 
                            <th>city_id</th>
                            <th>状态</th>
                            <th>操作</th> 
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}

{%block name='link'%} 

 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>
{%/block%} 
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
 <script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/sight/metalist.js" type="text/javascript"></script> 
 
{%/block%}