{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                         
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              景点总览 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">景点总览</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
                 <div class="clearfix"> 
                  <div class="col-xs-2 pull-right">   
                      <div class="checkbox"> 
                        <label>
                           <input type="checkbox" id="form-user_id" value="{%$userid%}" checked="">只看我发布的
                          </label>
                       </div> 
                   </div>  
                    <div class="col-xs-3 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入并选择景点" aria-describedby="sightName" id="form-sight" autocomplete="off">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-sight"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                    </div> 
                    <div class="col-xs-3 pull-right">   
                        <div class="input-group "> 
                             <input type="text" class="form-control" placeholder="输入并选择城市"  id="form-city" autocomplete="off">
                             <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-city"><i class="fa fa-remove"></i></button>
                            </span>
                          </div>
                    </div>  
                </div>  
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                             <th>ID</th>
                             <th>城市ID</th>
                            <th>名称</th>
                            <th>所属城市</th>
                            <th id="topicCount">相关话题</th>
                            <th id="keywordCount">相关词条</th> 
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/sight/situation.js" type="text/javascript"></script> 
 
{%/block%}