{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                         
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <div class="modal fade" id="generalTagModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    
                      <div class="modal-content">
                      <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                          <h4 class="modal-title">添加通用标签</h4>
                        </div>
                        <div class="modal-body"> 
                          <div class="form-group ">
                              <label for="name" class="control-label col-lg-2">通用标签:</label>
                              <div class="col-lg-5" id="generalTag-checkbox">
                                   
                              </div>
                          </div>    
                      </div>
                      <div class="modal-footer">
                        <button class="btn blue" type="submit" id="" data-status="1">保存</button> 
                         <button type="button" class="btn default" data-dismiss="modal">关闭</button>
                      </div>
                       <input type="hidden" name="id" id="sight-id" value=""/>
                       <input type="hidden" name="status" id="sight-status" value=""/>
                      </form> 
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              景点总览 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">景点总览</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
                 <div class="clearfix"> 
                  <div class="col-xs-2 pull-right">   
                      <div class="checkbox"> 
                        <label>
                           <input type="checkbox" id="form-user_id" value="{%$userid%}" >只看我发布的
                          </label>
                       </div> 
                   </div>  
                    <div class="col-xs-3 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入并选择景点" aria-describedby="sightName" id="form-sight" autocomplete="off">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-sight"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                    </div> 
                    <div class="col-xs-3 pull-right">   
                        <div class="input-group "> 
                             <input type="text" class="form-control" placeholder="输入并选择城市"  id="form-city" autocomplete="off" value="{%if isset($city)%}{%$city.name%}{%/if%}" data-city_id="{%if isset($city)%}{%$city.id%}{%/if%}">
                             <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-city"><i class="fa fa-remove"></i></button>
                            </span>
                          </div>
                    </div>  
                </div>  
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                            <th>景点ID</th> 
                            <th>名称</th>
                            <th>状态</th>
                            <th>所属城市/ID</th>
                            <th>
                              相关标签
                              <span class="label label-success">分类</span>
                              <span class="label label-warning">通用</span>
                              <span class="label label-default">普通</span>
                            </th>
                            <th id="topicCount">相关话题</th>
                            <th id="keywordCount">相关词条</th>
                            <th>相关书籍</th>
                            <th>相关视频</th> 
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/sight/situation.js" type="text/javascript"></script> 
 
{%/block%}