{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Modal title</h4>
						</div>
						<div class="modal-body">
							 Widget settings form goes here
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Save changes</button>
							<button type="button" class="btn default" data-dismiss="modal">Close</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			仪表板 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">仪表板</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN DASHBOARD STATS -->  
		    <div class="row state-overview"> 
            <div class="col-lg-3 col-sm-6">
                <section class="panel">
                    <div class="symbol terques">
                        <i class="fa fa-connectdevelop"></i>
                    </div>
                    <div class="value">
                        <h1 class="count2" id="topicNum">{%$topicNum%}</h1>
                        <p>总话题数(已发布)</p>
                    </div>
                </section>
            </div>
            <div class="col-lg-3 col-sm-6">
                <section class="panel">
                    <div class="symbol yellow">
                        <i class="fa fa-photo"></i>
                    </div>
                    <div class="value">
                        <h1 class=" count3" id="sightNum">{%$sightNum%}</h1>
                        <p>总景点数(已发布)</p>
                    </div>
                </section>
            </div>
            <div class="col-lg-3 col-sm-6">
                <section class="panel">
                    <div class="symbol red">
                        <i class="fa fa-forumbee"></i>
                    </div>
                    <div class="value">
                        <h1 class=" count4"></h1>
                        <p>主题数(已发布)</p>
                    </div>
                </section>
            </div>
            <div class="col-lg-3 col-sm-6">
                <section class="panel">
                    <div class="symbol blue">
                        <i class="fa fa-user"></i>
                    </div>
                    <div class="value">
                        <h1 class=" count3" id="sightNum"></h1>
                        <p>用户数</p>
                    </div>
                </section>
            </div>
        </div>
        <div class="row">
           <div class="col-lg-8"> 
               <div id="userRegTime-line"></div>
           </div>
        </div>
			<!-- END DASHBOARD STATS -->
		</div>
	</div>
{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/countup/countup.min.js" type="text/javascript"></script>
<!-- <script src="{%$feroot%}s/global/plugins/echarts/echarts-all.js" type="text/javascript"></script>  -->
<script>
   var sightNum = new CountUp("sightNum", 0, $('#sightNum').text()).start(); 
   //var topicNum = new CountUp("topicNum", 0, $('#topicNum').text()).start(); 

  
</script>  
{%/block%}