{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                      <form class="cmxform form-horizontal tasi-form" id="answerForm" method="post" action="" novalidate="novalidate" >
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">处理反馈</h4>
                      </div>
                      <div class="modal-body"> 
                         <div class="form-group ">
                              <label for="name" class="control-label col-lg-2">用户意见</label>
                              <div class="col-lg-10">
                                <textarea class="form-control" name="" id="user-content" cols="30" rows="5" disabled=""></textarea> 
                              </div>
                          </div> 
                          <div class="form-group ">
                              <label for="url" class="control-label col-lg-2">回复内容*</label>
                              <div class="col-lg-10">
                                <textarea class="form-control" name="content" id="content" cols="30" rows="5"></textarea> 
                              </div>
                          </div>   
                          <div class="form-group ">
                             <label for="status" class="control-label col-lg-2">选择状态*</label>
                             <div class="col-lg-10">
                             <select name="" id="form-status-add">
                             {%foreach $statusArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                             {%/foreach%}  
                             </select>
                             </div>
                          </div>    
                      </div>
                      <div class="modal-footer">
                        <button class="btn blue" type="button" id="addAnswer">确定</button> 
                         <button type="button" class="btn default" data-dismiss="modal">关闭</button>
                      </div>
                       <input type="hidden" name="" id="user-id" value=""/>
                      </form> 
                    </div>
                      <!-- /.modal-content -->
                  </div>
                  <!-- /.modal-dialog -->
              </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              意见反馈列表 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">意见反馈列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
              <input type="hidden" id="topicId" value="{%$topicId%}">
                 <div class="clearfix"> 
                    <div class="col-xs-2 pull-right">   
                        <div class="input-group ">
                          <select name="" id="form-status">
                             <option value="">全部状态</option>   
                             {%foreach $statusArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                             {%/foreach%}  
                          </select>
                       </div>
                    </div> 
                <!--    <div class="col-xs-2 pull-right">   
                     <div class="input-group ">
                       <select name="" id="form-type">
                          <option value="">全部类型</option>   
                          {%foreach $typeArray as $key=>$item%} 
                               <option value="{%$key%}">{%$item%}</option> 
                          {%/foreach%}  
                       </select>
                    </div>
                 </div>   -->
                </div>  
                 
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">
                            <th></th>  
                            <th>ID</th> 
                            <th>反馈人ID</th>
                            <th>反馈内容</th> 
                            <th>类型</th> 
                            <th>反馈时间</th> 
                            <th>处理人ID</th>
                            <th>处理时间</th> 
                            <th>&nbsp;&nbsp;状态&nbsp;&nbsp;</th>
                            <th>操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='script'%} 
<style>
   .answer-details table tr{
      border-bottom:1px dashed #666;
   } 
   .answer-details table tr:last-child{
      border-bottom:0px dashed #666;
   }
</style>
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/admin/advise/list.js" type="text/javascript"></script> 
 
{%/block%}