{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                      <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">添加文章景观</h4>
                        </div>
                        <div class="modal-body"> 
                                <div class="form-group ">
                                  <label for="name" class="control-label col-lg-2">名称*</label>
                                  <div class="col-lg-5">
                                      <input class="form-control" id="name" name="name"  type="text" required="" value=""><label for="name" class="error"></label>
                                  </div>
                              </div> 
                              <div class="form-group ">
                                  <label for="url" class="control-label col-lg-2">链接url</label>
                                  <div class="col-lg-4"> 
                                       <input class="form-control" id="url" name="url"  type="text" required="" value=""><label for="url" class="error"></label> 
                                  </div>
                                  <div class="col-lg-1"> 
                                        <a class="btn btn-default" target="_blank" id="view-link">查看</a> 
                                   </div>
                              </div>  
                              <div class="form-group ">
                                  <label for="sight_name" class="control-label col-lg-2">所属文章*</label>
                                  <div class="col-lg-5">
                                       <input  id="sight_id" name="sight_id"  type="hidden" value="">
                                       <input class="form-control" id="sight_name" name="sight_name"  type="text" disabled="disabled" autocomplete="off" value=""/> 
                                       <label for="sight_name" class="error"></label>
                                  </div>
                              </div> 
                             
                        </div>
                        <div class="modal-footer">
                            <button class="btn blue" type="submit" id="" data-status="1">只保存</button>
                            <button class="btn btn-danger" type="submit" id="" data-status="2">确认并保存</button>
                             <button type="button" class="btn default" data-dismiss="modal">关闭</button>
                        </div>
                         <input type="hidden" name="status" id="status" value=""/>
                        </form> 
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              文章推荐管理 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">文章推荐管理</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
                 <div class="clearfix"> 
                     <div class="btn-group  hidden">
                      <a  class="btn  btn-success" href="/admin/sight/edit">
                          添加 <i class="fa fa-plus"></i>
                      </a>
                  </div>
                  <div class="col-xs-3  pull-right hidden"> 
                            <input type="text" class="form-control" id="form-title" placeholder="输入标题点回车"> 
                  </div>  
                      <div class="col-xs-2 pull-right">   
                          <div class="input-group ">
                            <select name="" id="form-status">
                                <option value="">全部状态</option>  
                               {%foreach $statusArray as $key=>$item%} 
                                    <option value="{%$key%}">{%$item%}</option> 
                               {%/foreach%}  
                            </select>
                         </div>
                       </div>  
                   <div class="col-xs-3 pull-right">   
                              <div class="input-group "> 
                                <input type="text" class="form-control" placeholder="输入并选择景点" aria-describedby="sightName" id="form-sight" autocomplete="off">
                                <span class="input-group-btn">
                                <button type="button" class="btn btn-white" id="clear-sight"><i class="fa fa-remove"></i></button>
                              </span>
                             </div>
                      </div>  
                     <div class="col-xs-3 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入并选择通用标签" id="form-tag" autocomplete="off">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-tag"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                      </div>  
                  </div>   
                  </div>  
                <div id="test"></div>
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                            <th rowspan="2" class="mainth">文章ID</th> 
                            <th rowspan="2" class="mainth">文章标题</th>
                            <th rowspan="2" class="mainth">副标题</th>  
                            <th rowspan="2" class="mainth">推荐标签</th>  
                            <th colspan="3">
                              推荐结果
                                <span class="label label-danger">景点</span>
                                <span class="label label-warning">标签</span>
                            </th>
                          </tr>
                          <tr role="row"> 
                              <th>推荐对象</th> 
                              <th>评分</th>   
                              <th>当前状态</th>
                              <th>选择状态</th>   
                              <th>操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='link'%}  
<link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>
<style type="text/css" media="screen">
   .table-scrollable > .table-bordered > tbody > tr.group > td:last-child{
    border-right: 1px solid #ddd;;
   }
 </style> 
{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/recommend/articlerecommend.js" type="text/javascript"></script> 
 
{%/block%}