{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM--> 
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>  
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
            用户管理 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">用户管理</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS -->   
            <div class="adv-table editable-table"> 
                <div class="col-xs-2 pull-right"> 
                    <div class="input-group ">
                        <select name="" id="form-sex"> 
                            <option value="">全部性别</option> 
                             {%foreach $sexArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                            {%/foreach%}  
                        </select>
                    </div>
                </div> 
                <div class="col-xs-3 pull-right">
                    <div class="input-group input-group"> 
                      <input type="text" class="form-control" placeholder="输入并选择城市" aria-describedby="city_name" id="form-city" autocomplete="off"/>
                      <span class="input-group-btn">
                         <button type="button" class="btn btn-white" id="clear-city"><i class="fa fa-remove"></i></button>
                      </span>
                    </div>
                </div>
                <div class="col-xs-3 pull-right"> 
                    <input type="text" class="form-control" id="form-device_id" placeholder="输入设备ID点回车"> 
                </div> 
                <div class="col-xs-3 pull-right"> 
                    <input type="text" class="form-control" id="form-nick_name" placeholder="输入昵称点回车"> 
                </div> 
            </div>
               <table class="table table-striped table-hover table-bordered dataTable " id="editable">
                     <thead>
                         <tr role="row">  
                            <th>ID</th>
                            <th>设备ID</th>
                            <th>昵称</th>
                            <th>所在城市</th>
                            <th>性别</th>
                            <th>头像</th>
                            <th>接收消息</th>
                            <th>注册时间</th>
                            <th>上次登录时间</th>
                            <th>操作</th> 
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             <!-- END content STATS --> 
    </div> 
{%/block%}
{%block name='link'%}   
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/>  
 

{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/user/index.js" type="text/javascript"></script>    
{%/block%}

