{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content"> 
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">创建话题来源</h4>
              </div>
              <div class="modal-body">
                  <form id="source" >
                     <input type="hidden"  id="source-type"/>
                     <input type="hidden"  id="source-id"/>
                  <div class="form-group source-name" >
                    <label for="source-name" class="control-label">名称:</label>
                    <input type="text" class="form-control" id="source-name">
                  </div>
                  <div class="form-group source-type" >
                    <label for="source-type" class="control-label">类型:</label>
                    <label class="radio-inline">
                        <input type="radio" name="type" data-name="source-type" id="" value="1" data-type="1">微信公众号
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="type" data-name="source-type" id="" value="2" data-type="2" checked="">其他
                      </label>    
                  </div>
                  <div class="form-group source-url">
                    <label for="source-url" class="control-label">网址url(不要http 例如：zhihu.com)</label>
                    <input type="text" class="form-control" id="source-url">
                  </div> 
                </form> 
              </div>
              <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              <button type="button" class="btn btn-primary" id="addSource-btn">保存</button>
            </div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			话题来源管理 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">话题来源管理</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		    <div class="adv-table editable-table ">
		    	<div class="clearfix">
                  <div class="btn-group">
                      <button id="editable-new" class="btn  btn-success openSource">
                          添加 <i class="fa fa-plus"></i>
                      </button>
                  </div> 
                </div>

                <div class="col-xs-2 pull-right">   
                      <div class="checkbox"> 
                        <label>
                           <input type="checkbox" id="form-user_id" value="{%$userid%}" checked="">只看我发布的
                          </label>
                     </div> 
                </div> 
                <div class="col-xs-2 pull-right">   
                    <div class="input-group ">
                      <select name="" id="form-type"> 
                        <option value="">全部类型</option> 
                           <option value="1">微信公众号</option>  
                           <option value="2">其他</option>
                      </select>
                   </div>
                </div>  
                <div class="col-xs-3  pull-right"> 
                            <input type="text" class="form-control" id="form-title" placeholder="输入标题点回车"> 
                </div>
               <table class="table table-striped table-hover table-bordered dataTable DTTT_selectable" id="editable">
                     <thead>
                         <tr role="row">  
                         	<th>ID</th>
			                <th>名称</th>
			                <th>url</th>
			                <th>创建时间</th>
			                <th>更新时间</th>
			                <th>操作</th>  
		                  </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
		     
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%} 
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/admin/source/index.js" type="text/javascript"></script> 

<!--  <link href="{%$feroot%}s/global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">
<script src="{%$feroot%}s/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js"></script> -->

	<script>
  
	</script>
{%/block%}