{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content"> 
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}消息 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/msg/list">消息管理</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}消息</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.mid)%}
                    <input type="hidden" name="mid" id="mid" value="{%$post.mid%}"/>
                    {%/if%}  
                      <div class="form-group ">
                          <label for="title" class="control-label col-lg-2">标题*</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="title" name="title"  type="text" required="" value="{%if isset($post.title)%}{%$post.title%}{%else%}系统消息{%/if%}"/>
                              <label for="title" class="error"></label> 
                          </div>
                      </div> 
                      <div class="form-group ">
                          <label for="content" class="control-label col-lg-2">内容*</label>
                          <div class="col-lg-5">
                          	<textarea name="content" id="content" cols="60" rows="5">{%if isset($post.content)%}{%$post.content%}{%/if%}</textarea> 
                              <label for="content" class="error"></label> 
                          </div>
                      </div> 
                       {%if isset($post.mid)%}
                      <div class="form-group ">
                          <label for="type" class="control-label col-lg-2">类型:</label>
                          <div class="col-lg-2">
                              <input class="form-control" id="type" name="type"  type="text" disabled="" value="{%if isset($post.type)%}{%$post.type_name%}{%else%}系统消息{%/if%}"/>
                              <label for="type" class="error"></label> 
                          </div>
                      </div> 
                      <div class="form-group ">
                          <label for="image" class="control-label col-lg-2">状态:</label>
                          <div class="col-lg-2">
                          	 <input class="form-control" id="type" name="type"  type="text" disabled="" value="{%if isset($post.type)%}{%$post.status_name%}{%/if%}"/>
                              <label for="type" class="error"></label>  
                          </div>
                      </div> 
                        {%if empty($post.image) eq 0%}  
                        <div class="form-group ">
                            <label for="image" class="control-label col-lg-2">图片:</label>
                            <div class="col-lg-5"> 
                                <img src="/pic/{%$post.image%}@f120w_f90h" alt="">
                                <label for="image" class="error"></label> 
                            </div>
                        </div>
                        {%/if%}
                       {%/if%} 
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                              {%if !isset($disabled)%}  
                                <button class="btn btn-danger" type="submit" data-action="send">发送</button>
                               <!--  <button class="btn btn-danger" type="submit" id="" data-status="2">定时发送</button> -->
                              {%/if%} 
                                {%if isset($post.mid)%} 
                                 <a class="btn btn-default"  href="/admin/msg/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%} 
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/msg/edit.js" type="text/javascript"></script> 

 
{%/block%}