{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
           			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content">
					  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">为标签关联城市或景点</h4>
						</div>
						<div class="modal-body"> 
							 	<div class="form-group ">
		                          <label for="name" class="control-label col-lg-2">选择城市：</label>
		                          <div class="col-lg-5">
		                          {%foreach $city as $key => $item%}
						            <input class="form-control" id="name" name="obj_id"  type="checkbox" required="" value={%$item.id%}>{%$item.name%}<label for="name" class="error"></label>
						          {%/foreach%} 		                              
		                          </div>
		                      </div> 	
		                      
		                      <div class="form-group ">
		                          <label for="name" class="control-label col-lg-2">选择景点:</label>
		                          <div class="col-lg-5">
		                          {%foreach $sight as $key => $item%}
						            <input class="form-control" id="name" name="obj_id"  type="checkbox" required="" value={%$item.id%}>{%$item.name%}<label for="name" class="error"></label>
						          {%/foreach%} 		                              
		                          </div>
		                      </div>					 
						</div>
					
						<div class="modal-footer">
							<button class="btn blue" type="submit" id="" data-status="1">保存</button>
							 <button type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
						 <input type="hidden" name="status" id="status" value=""/>
						</form> 
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              搜索标签列表 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">搜索标签列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table "> 
                 <div class="clearfix">
                    <div class="btn-group">
                      <a  class="btn  btn-primary" href="/admin/search/edit" id="xxx">
                          添加搜索标签 <i class="fa fa-plus"></i>
                      </a>
                    </div>  
                </div>  
                <br>
               <div class="col-lg-3">
                           	 <div class="alert alert-info" role="alert" id="sight_alert">
                                  {%foreach $sightList as $key=>$item%}
                                  <span class="badge badge-sm label-danger" role="badge">                                    
                                    <span  class="click" data-id="{%$item.id%}" id="search-id">{%$item.name%}({%$item.obj_num%})</span>
                                    <button type="button" class="close" data-id="{%$item.id%}"><span class="fa fa-remove"></span></button>
                                  </span> 
                                   {%/foreach%}  
                             </div>
               </div>  
                
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row"> 
                            <th>ID</th>
                            <th>名称</th>
                            <th>类型</th>
                            <th>对象ID</th>
                            <th>对象名</th>
                            <th>创建时间</th>
                            <th>更新时间</th> 
                            <th>操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='script'%} 
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/admin/search/list.js" type="text/javascript"></script> 
 
{%/block%}