{%extends file="common/page.phtml"%}
{%block name="script"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/home/css/interest.css" /> 
<script>
    require(['home/index'], function (main) {
        //main.init();
    }); 
</script>
<style type="text/css" media="screen">
  
</style>
{%/block%}

{%block name="content"%}  
<div class="tuzhi diversified container">
     <div class="tuzhi_img " id="tuzhi_img_box"> 
     </div>
     <div class="copyright">
          Copyright © 2015-2016 途知. All rights reserved. 
     </div> 
     <div class="footer"> 
     </div> 
     <div class="content centered">
        <ul class="menus clearfix">
            <li class="index"><a href="/index">首页</a></li>
            <li class="interest"><a href="/interest">有趣生动</a></li>
            <li class="overall"><a href="/overall">覆盖全面</a></li>
            <li class="diversified active"><a href="/diversified">形式多样</a></li>
        </ul>
        <div class="tuzhi_box" id="tuzhi_box">  
         <div class="ours rel" id="ours"> 
              
                <div class="logo_pc clearfix">
                    <!-- <div class="logo_img"></div> -->
                    <img src="{%$feroot%}/home/img/app-logo.png" alt="" class="logo_img">
                    <div class="logo_text">
                        目不暇接，丰富内容尽在掌握
                    </div> 
                </div>
               <div class="phone1 abs">
                    <img src="{%$feroot%}/home/img/iphone6Gold_diversified.png" alt="" class="logo_img">
                </div>
               <div class="download_box abs">
                   <div class="logo rel"> 
                    <div class="logo_text">
                        内容精美形式多样 
                    </div>
                    <div class="logo_text2 abs">  
                        旅行中自己拍的照片固然好看，但途知里的图片都是小<br>编精心搜罗而来，和文字一样精彩纷呈甚至是意想不<br>到。形式也不再拘泥于游记、路线、攻略，<br>
                        除了这些处处可见的内容，途知会带给你更多。
                    </div>  
                </div>
                  <div class="download">
                    <a class="apple_logo" href="/download" target="_blank"><img src="{%$feroot%}/home/img/apple_download.png" alt="" class="slogan_img"></a><div class="erweima "><img src="{%$feroot%}/home/img/erweima.png" alt="" class="slogan_img"></div> 
               </div>  
             </div> 
              
         
           
         </div> 
     </div> 
     </div>
 
</div>
 
{%/block%}
