{%extends file='common/layout.phtml'%}
{%block name='content'%} 
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog  modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">添加视频信息</h4>
						</div>
						<div class="modal-body">
							  
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">保存</button>
							<button type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
       {%include file='utils/corpimg.phtml'%}
        {%include file='utils/map.phtml'%}
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE HEADER-->
			<h3 class="page-title">
			  {%$action%}视频 <small>reports & statistics</small>
			</h3>
			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-home"></i>
						<a href="/admin">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<i class="fa fa-list-ul"></i>
						<a href="/admin/video/list">视频管理</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="#">{%$action%}视频</a>
					</li>
				</ul>
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN content STATS --> 
		     <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/>
                    <div class="form-group ">
                          <label for="title" class="control-label col-lg-2">当前状态:</label>
                          <label class="control-label col-lg-2" style="text-align: left;">
                            {%$post.statusName%} 
                          </label>
                    </div> 
                    <div class="form-group ">
                        <label for="guid" class="control-label col-lg-2">视频唯一标识码：</label>
                        <label class="control-label col-lg-2" style="text-align: left;">
                            {%if isset($post.guid)%}{%$post.guid%}{%/if%}
                        </label>
                    </div> 
                    {%/if%}
                    <div class="form-group ">
                        <label for="title" class="control-label col-lg-2">视频名称*：</label>
                        <div class="col-lg-5">
                            <input class="form-control" id="title" name="title"  type="text" required="" value="{%if isset($post.title)%}{%$post.title%}{%/if%}"><label for="title" class="error"></label>
                        </div>
                    </div> 
                    <div class="form-group ">
                        <label for="url" class="control-label col-lg-2">链接*：</label>
                        <div class="col-lg-4">
                            <input class="form-control" id="url" name="url"  type="text" required="" value="{%if isset($post.url)%}{%$post.url%}{%/if%}"><label for="url" class="error"></label>
                        </div>
                        <div class="col-lg-1"> 
                            <a class="btn btn-default" target="_blank" id="view-link" href="{%if isset($post.url)%}{%$post.url%}{%/if%}">查看</a> 
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="from" class="control-label col-lg-2">来源：</label>
                        <div class="col-lg-5">
                            <input class="form-control" id="from" name="from"  type="text" required="" value="{%if isset($post.from)%}{%$post.from%}{%/if%}"><label for="from" class="error"></label>
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="len" class="control-label col-lg-2">长度：</label>
                        <div class="col-lg-5">
                            <input class="form-control" id="len" name="len"  type="text" required="" value="{%if isset($post.len)%}{%$post.len%}{%/if%}"><label for="len" class="error"></label>
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="type" class="control-label col-lg-2">类型：</label>
                        <div class="col-lg-5"> 
                            <select name="type" id="form-type" class="form-control" >  
                                 {%foreach $typeArray as $key=>$item%} 
                                  <option value="{%$key%}" {%if isset($post.type) and $key eq $post.type%}selected{%/if%}>{%$item%}</option> 
                                 {%/foreach%}  
                            </select> 
                            <label for="type" class="error"></label>
                        </div>
                    </div>
                     <div class="form-group ">
                        <label for="sight_id" class="control-label col-lg-2">景点*：</label>
                        <div class="col-lg-5">  
                           <div class="input-group "> 
                              <input class="form-control" id="sight_name" name="sight_name" type="text"  autocomplete="off"  placeholder="输入景点后请在下拉框选择" value="{%if isset($post.sight_name)%}{%$post.sight_name%}{%/if%}" data-sight_id="{%if isset($post.sight_id)%}{%$post.sight_id%}{%/if%}"/> 
                              <span class="input-group-btn">
                                <button type="button" class="btn btn-white" id="clear-sight"><i class="fa fa-remove"></i></button>
                              </span>
                           </div>
                           <label for="sight_id" class="error"></label>
                        </div>
                     </div>
                    <div class="form-group"> 
                          <label for="" class="control-label col-lg-2">图片</label>
                          <div class="col-md-9">
                              <div class="fileupload fileupload-new" data-provides="fileupload">
                                  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                      <img src="{%$feroot%}s/global/img/no_image.png" alt="">
                                  </div>
                                  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                  </div>
                                  <div id="imageView" class="imageView thumbnail {%if isset($post.image)%}imagedis{%/if%}" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                    {%if empty($post.image) eq 0%}  
                                     <img src="{%$webroot%}/pic/{%$post.image%}@f190w_f80h" alt=""> 
                                    {%/if%}
                                  </div> 
                                    <button id="crop-img" class="btn btn-primary fileupload-crop{%if empty($post.image)==1%} hidden{%/if%}" type="button" data-corpUrl="sight"><i class="fa fa-cut"></i>裁剪</button>
                                    <input type="hidden" id="jcrop-ratio" data-width="414" data-height="166"/>
                                  <div>
                                   <span class="btn btn-white btn-file">
                                   <span class="fileupload-new"><i class="fa fa-paper-clip"></i> 选择文件</span>
                                   <span class="fileupload-exists"><i class="fa fa-undo"></i> 换一张</span>
                                   <input type="file" class="default" name="file" id="imageBtn" />
                                   <input type="hidden" name="image" id="image" value="{%if isset($post.image)%}{%$post.image%}{%/if%}" />
                                   </span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> 移除</a>
                                    <button id="upload-img" class="btn btn-success fileupload-exists" data-dismiss="fileupload"><i class="fa fa-cloud-upload"></i> 上传</button>
                                  </div>
                              </div> 
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                               <button class="btn btn-danger" type="submit" id="submitBtn" data-action="NOTPUBLISHED" data-btn_text="保存">保存</button>
                               <button class="btn btn-danger" type="submit" data-action="PUBLISHED" data-btn_text="发布">发布</button>
                               {%if isset($post.id)%} 
                                 <a class="btn btn-default"  href="/admin/video/list">返回列表</a> 
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%}
                              
                          </div>
                      </div>
                  </form>
              </div>
			<!-- END content STATS -->
		</div>
	</div>

{%/block%}
{%block name='link'%} 
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/> 
{%/block%}
{%block name='script'%}   
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
 
<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jcrop/js/jquery.Jcrop.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/video/edit.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/utils/cropimg/index.js" type="text/javascript"></script> 

 
{%/block%}