{%extends file='common/layout.phtml'%} 
{%block name='content'%} 
  <div class="page-content-wrapper">
    <div class="page-content">
      <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog  modal-lg">
           <div class="modal-content"> 
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">创建主题来源</h4>
              </div>
              <div class="modal-body">
                <form id="source" >
                  <input type="hidden"  id="source-type"/>
               <div class="form-group source-name" >
                 <label for="source-name" class="control-label">名称*:</label>
                 <input type="text" class="form-control" id="source-name">
               </div>
               <div class="form-group source-url">
                 <label for="source-url" class="control-label">网址url(不要http 例如：zhihu.com ,杂志类的可以不填)</label>
                 <input type="text" class="form-control" id="source-url">
               </div> 
             </form> 
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="addSource-btn">创建</button>
               </div>
            </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      {%include file='utils/corpimg.phtml'%}
      <div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog  modal-lg">
           <div class="modal-content"> 
             </div>
          /.modal-content
        </div>
        /.modal-dialog
      </div>
      <!-- /.modal -->
      <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <!-- BEGIN PAGE HEADER-->
      <h3 class="page-title">
        {%$action%}主题 <small>reports & statistics</small>
      </h3>
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li>
            <i class="fa fa-home"></i>
            <a href="/admin">Home</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <i class="fa fa-list-ul"></i>
            <a href="/admin/theme/list">主题列表</a>
            <i class="fa fa-angle-right"></i>
          </li>
          <li>
            <a href="#">{%$action%}主题</a>
          </li>
        </ul>
      </div>
      <!-- END PAGE HEADER-->
      <!-- BEGIN content STATS --> 
         <div class=" form">
                  <form class="cmxform form-horizontal tasi-form" id="Form" method="post" action="" novalidate="novalidate" >
                    {%if isset($post.id)%}
                    <input type="hidden" name="id" id="id" value="{%$post.id%}"/> 
                     <div class="form-group ">
                          <label for="title" class="control-label col-lg-2">当前状态:</label>
                          <label class="control-label col-lg-2" style="text-align: left;">
                               {%$post.statusName%} 
                          </label>
                      </div>
                    {%/if%} 
                      <div class="form-group ">
                          <label for="name" class="control-label col-lg-2">主标题*:</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="name" name="name"   type="text" value="{%if isset($post.name)%}{%$post.name%}{%/if%}" >
                              <label for="name" class="error"></label>
                          </div>  
                      </div>
                      <div class="form-group ">
                          <label for="title" class="control-label col-lg-2">副标题：</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="title" name="title"   type="text"  value="{%if isset($post.title)%}{%$post.title%}{%/if%}">
                              <label for="title" class="error"></label>
                          </div> 
                      </div> 
                      <div class="form-group ">
                          <label for="period" class="control-label col-lg-2">主题期数*:</label>
                          <div class="col-lg-5">
                              <input class="form-control" id="period" name="period"   type="text"  value="{%if isset($post.period)%}{%$post.period%}{%/if%}"><label for="period" class="error"></label>
                          </div>
                      </div>   
                      <div class="form-group ">
                          <label for="landscape_name" class="control-label col-lg-2">包含景观*</label>
                          <div class="col-lg-3"> 
                               <input class="form-control" id="landscape_name"    type="text"  autocomplete="off"  placeholder="输入后请在下拉框选择"/>  
                               <span class="help-block">
                                  没有想要的景观？<a href="/admin/landscape/edit" class="" target="_blank">创建</a>一个
                              </span> 
                          </div>
                           <div class="col-lg-3">
                             <div class="alert alert-info" role="alert" id="landscape_alert">
                                 {%foreach $landscapeList as $key=>$item%}
                                 <span class="badge badge-sm label-danger" role="badge">   {%$item.name%}
                                   <button type="button" class="close" data-id="{%$item.id%}"><span class="fa fa-remove"></span></button>
                                 </span> 
                                  {%/foreach%}  
                             </div> 
                           </div> 
                           
                      </div>   
                      <div class="form-group"> 
                          <label for="" class="control-label col-lg-2">背景图片*：</label>
                          <div class="col-md-9">
                              <div class="fileupload fileupload-new" data-provides="fileupload">
                                  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                      <img src="{%$feroot%}s/global/img/no_image.png" alt="">
                                  </div>
                                  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                  </div>
                                  <div id="imageView" class="imageView thumbnail {%if empty($post.image)==0%}imagedis{%/if%}" style="width:200px;height:150px;max-width: 200px; max-height: 150px; line-height: 20px;"> 
                                    {%if !empty($post.image)%} 
                                     <img src="{%$webroot%}/pic/{%$post.image%}@f190w_f140h" alt=""> 
                                    {%/if%}
                                  </div>
                                  <button id="crop-img" class="btn btn-primary fileupload-crop{%if empty($post.image)==1%} hidden{%/if%}" type="button" data-corpUrl="theme"><i class="fa fa-cut"></i>裁剪</button>
                                  <input type="hidden" id="jcrop-ratio" data-width="133" data-height="93"/>
                                  <div>
                                   <span class="btn btn-white btn-file">
                                   <span class="fileupload-new"><i class="fa fa-paper-clip"></i> 选择文件</span>
                                   <span class="fileupload-exists"><i class="fa fa-undo"></i> 换一张</span>
                                   <input type="file" class="default" name="file" id="imageBtn" />
                                   <input type="hidden" name="image" id="image" value="{%if isset($post.image)%}{%$post.image%}{%/if%}" />
                                   </span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> 移除</a>
                                    <button id="upload-img" class="btn btn-success fileupload-exists" data-dismiss="fileupload"><i class="fa fa-cloud-upload"></i> 上传</button>

                                  </div>
                              </div> 
                          </div>
                      </div>  
                      <div class="form-group ">
                          <label for="summernote" class="control-label col-lg-2">正文：<br/>(注：若想从服务器删除图片，请选中图片点击删除按钮)</label>
                          <div class="col-lg-10">
                              <div id="summernote" ></div>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-lg-offset-2 col-lg-10">
                            {%if !isset($disabled)%} 
                              <button class="btn btn-danger" type="submit"   data-action="NOTPUBLISHED" data-btn_text="保存">保存</button>
                              <button class="btn btn-danger" type="submit" data-action="PUBLISHED" data-btn_text="发布">发布</button>
                            {%/if%}
                               {%if isset($post.id)%}
                                 <a class="btn btn-default"  href="/admin/theme/list">返回列表</a>  
                                {%else%}
                                <button class="btn btn-default"  name="reset"  type="reset">重置</button> 
                                {%/if%}
                              
                          </div>
                      </div>
                  </form>
              </div>
      <!-- END content STATS -->
    </div>
  </div>
<div id="content-text" style="display:none;"> 
  {%if isset($post.content)%}
  {%$post.content%} 
  {%/if%} 
</div>
 {%if isset($post.id) eq 0%}
    <script type="text/javascript"> 
        $('#content-text').html(localStorage.themeContent);
     </script>
  {%/if%}
{%/block%}

{%block name='link'%}
 <link href="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css"/>  
 <link href="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote.css" rel="stylesheet" type="text/css"/>  
{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 

<script src="{%$feroot%}s/global/plugins/bootstrap-fileupload/bootstrap-fileupload.js" type="text/javascript"></script> 
   
<script src="{%$feroot%}s/global/plugins/ajaxfileupload.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote_new.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-summernote/summernote-zh-CN.js" type="text/javascript"></script>   
<script src="{%$feroot%}s/global/plugins/jcrop/js/jquery.Jcrop.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/theme/edit.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/admin/utils/cropimg/index.js" type="text/javascript"></script> 

  

 
{%/block%}