{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                      
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              话题列表 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">话题列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
                 <div class="clearfix"> 
                     <div class="btn-group">
                      <a  class="btn  btn-primary" href="/admin/topic/edit">
                          添加 <i class="fa fa-plus"></i>
                      </a>
                  </div> 

                    <div class="col-xs-2 pull-right">   
                          <div class="checkbox"> 
                            <label>
                               <input type="checkbox" id="form-user_id" value="{%$userid%}" checked="">只看我发布的
                              </label>
                         </div> 
                    </div> 
                   <div class="col-xs-2 pull-right">   
                        <div class="input-group ">
                          <select name="" id="form-status"> 
                            <option value="">全部状态</option> 
                             {%foreach $statusTypeArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                            {%/foreach%}  
                          </select>
                       </div>
                  </div>
                    <div class="col-xs-3  pull-right"> 
                            <input type="text" class="form-control" id="form-title" placeholder="输入标题点回车"> 
                    </div>   
                     <div class="col-xs-3 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入并选择景点" aria-describedby="sightName" id="form-sight" autocomplete="off">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-sight"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                    </div>  
                </div>  
                 
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                         <tr role="row">  
                            <th>ID</th>
                            <th>&nbsp;</th>
                            <th>标题</th>
                            <th>来源</th>
                            <th>原文链接</th> 
                            <th class="">相关景点</th>
                            <th class="">背景图片</th>
                            <th class="">收藏数</th>
                            <th class="">评论数</th>
                            <th class="">状态</th> 
                            <th class="">操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='script'%} 
<!--  <link href="{%$feroot%}s/global/plugins/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/> -->
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script> 
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
<script src="{%$feroot%}s/admin/topic/index.js" type="text/javascript"></script> 
 
{%/block%}