{%extends file="common/page.phtml"%}
{%block name="script"%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/home/css/index.css" /> 
<script>
    require(['home/index'], function (main) {
        main.init();
    }); 
</script>
<style type="text/css" media="screen">
 
    .mobile .ours{
        height: initial;
    }

</style>
{%/block%}

{%block name="content"%}
 <div class="tuzhi container {%if $isMobile%}mobile{%/if%} ">
     <div class="tuzhi_img abs" id="tuzhi_img_box">
         <!-- <img src="{%$feroot%}/home/img/tuzhi_index.png" alt="" class="click-through abs">     -->
     </div>
     <div class="tuzhi_box centered" id="tuzhi_box">
        <div class="download rel">
            <a class="apple_logo" href="/download" target="_blank"><img src="{%$feroot%}/home/img/apple.png" alt="" class="slogan_img"></a>
            <!-- <div class="hy abs"></div> -->
            <div class="erweima "><img src="{%$feroot%}/home/img/erweima.png" alt="" class="slogan_img"></div>
            <!-- <div class="more_than abs"></div> -->
        </div>
         <div class="ours abs" id="ours">
             
                 <div class="slogan abs">
                    <img src="{%$feroot%}/home/img/map-marker.png" alt="" class="slogan_img">
                    了解旅行中的历史、文化、科学等知识
                 </div> 
                <div class="logo abs">
                    <!-- <div class="logo_img"></div> -->
                    <img src="{%$feroot%}/home/img/app-logo.png" alt="" class="logo_img">
                    <div class="logo_text">
                        <span class="app_name">途知</span>
                        <span class="app_slogan">深度旅行</span> 
                    </div> 
                </div>
                <div class="phone1 abs">
                    <img src="{%$feroot%}/home/img/phone1.png" alt="" class="logo_img">
                </div>
                <div class="phone2 abs">
                     <img src="{%$feroot%}/home/img/phone2.png" alt="" class="">  
                </div> 
                <div class="phone3"></div>
         
           
         </div> 
     </div> 
 </div>
{%/block%}
