{%extends file='common/layout.phtml'%}
{%block name='content'%} 
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                    <div class="modal-content">
                     <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                       <h4 class="modal-title">排序</h4>
                     </div>
                     <div class="modal-body">
                      <ul id="sortable"></ul>
                     </div>
                      <div class="modal-footer"> 
                         <button type="button" class="btn default" data-dismiss="modal">关闭</button>
                      </div>  
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            {%include file='utils/uploadpic.phtml'%}
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN PAGE HEADER-->
            <h3 class="page-title">
              美食管理 <small>reports & statistics</small>
            </h3>
            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">美食列表</a>
                    </li>
                </ul>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN content STATS --> 
            <div class="adv-table editable-table ">
                 <div class="clearfix"> 
                   <div class="btn-group  pull-left">
                     <a  class="btn  btn-primary" href="/admin/food/edit?action=add">
                         添加 <i class="fa fa-plus"></i>
                     </a>
                   </div> 
                   <div class="col-xs-2 pull-right">   
                        <div class="input-group ">
                          <select name="" id="form-status">
                             <option value="">全部状态</option>   
                             {%foreach $statusArray as $key=>$item%} 
                                  <option value="{%$key%}">{%$item%}</option> 
                             {%/foreach%}  
                          </select>
                   </div>
                 </div>
                  <div class="col-xs-2 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入选择城市" aria-describedby="cityName" id="form-city" autocomplete="off"  value="{%if isset($city)%}{%$city.name%}{%/if%}" data-city_id="{%if isset($city)%}{%$city.id%}{%/if%}">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-city"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                    </div>
                  <div class="col-xs-2 pull-right">   
                            <div class="input-group "> 
                              <input type="text" class="form-control" placeholder="输入选择景点" aria-describedby="sightName" id="form-sight" autocomplete="off"  value="{%if isset($sight)%}{%$sight.name%}{%/if%}" data-sight_id="{%if isset($sight)%}{%$sight.id%}{%/if%}">
                              <span class="input-group-btn">
                              <button type="button" class="btn btn-white" id="clear-sight"><i class="fa fa-remove"></i></button>
                            </span>
                           </div>
                    </div>
                    
                  <div class="col-xs-3  pull-right"> 
                        <input type="text" class="form-control" id="form-title" placeholder="输入名称点回车"> 
                    </div> 
                   
   
                   </div>
                 
               <table class="table table-striped table-hover table-bordered dataTable" id="editable">
                     <thead>
                        <tr role="row">  
                            <th class="mainth">ID</th> 
                            <th class="mainth">名称</th>
                            <th class="mainth">图片</th>  
                            <th class="mainth">简介</th> 
                            <th class="mainth">状态</th>
                            <th class="mainth">店铺列表</th>
                            <th class="mainth">
                                                                     所属目的地
                                <span class="label label-danger">景点</span>
                                <span class="label label-warning">城市</span>
                            </th> 
                            <th class="mainth">操作</th>  
                          </tr>
                      </thead>
                      <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                       </tbody>
                </table> 
             
            <!-- END content STATS -->
        </div>
    </div>

{%/block%}
{%block name='link'%}  
 <link href="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/> 
 <link href="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css"/> 
{%/block%}
{%block name='script'%}  
<script src="{%$feroot%}s/global/plugins/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/typeahead/bootstrap-typeahead.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/admin/food/index.js" type="text/javascript"></script>  
{%/block%}