<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>途知</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="{%$feroot%}s/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="{%$feroot%}s/admin/pages/css/login.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="{%$feroot%}s/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="{%$feroot%}s/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGO -->
<div class="logo">
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div class="content">
	<!-- BEGIN LOGIN FORM --> 
    <form class="login-form" id="Form"  action="" novalidate="novalidate">
		<h3 class="form-title">后台登录</h3>
		<div class="alert alert-danger display-hide">
			<button class="close" data-close="alert"></button>
			<span></span>
		</div>
		<div class="form-group">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			<label class="control-label visible-ie8 visible-ie9">用户名</label>
			<input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="用户名" name="name"/>
		</div>
		<div class="form-group">
			<label class="control-label visible-ie8 visible-ie9">密码</label>
			<input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="密码" name="passwd"/>
		</div>
<!-- 		<div class="form-group">
	<label class="control-label visible-ie8 visible-ie9">验证码</label>
	<input autocomplete="off" class="form-control form-control-solid placeholder-no-fix" id="login-testing" type="text" />
	 <a href="###" class="login-username-testing">
              <img id="login-img-url" src="{%$url%}" width="162" height="35" />
          </a>
</div>  -->
		 
                   
		<div class="form-actions">
			<button type="button" class="btn btn-success uppercase" id="loginBtn">登录</button>
			<!-- <label class="rememberme check">
			<input type="checkbox" name="remember" value="1"/>Remember </label> -->
		</div>
		<div class="create-account">
			<p>
			</p>
		</div>
	</form>
	<!-- END LOGIN FORM -->
</div>
<div class="copyright">
	 2015 © 北京百年兴教网络技术有限公司 京ICP备14061443号
</div>
<!-- END LOGIN -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{%$feroot%}s/global/plugins/respond.min.js"></script>
<script src="{%$feroot%}s/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="{%$feroot%}s/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{%$feroot%}s/global/scripts/metronic.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/scripts/emitter.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/scripts/Remoter.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/pages/scripts/login.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {     
	Metronic.init(); // init metronic core components
	Layout.init(); // init current layout
	Login.init();
	//Demo.init();
	
/*	{%if !empty($result.statusInfo)%}
	Login.alert('{%$result.statusInfo%}');
	{%/if%}*/
 	$(document).keydown(function(event){ 
 	   //绑定回车
		if(event.keyCode == 13){ 
		//自动触发登录按钮
		   $('#loginBtn').click(); 
		}
	}); 
    $('#loginBtn').click(function(event) {  
    	var login=new Remoter('/admin/AdminUserapi/login');
        login.remote({
            name:$('input[name="name"]').val(),
            password:$('input[name="passwd"]').val(),
            redirectUri:'{%$redirectUri%}'
        }); 
    });
	 
});
</script>

</body>

<!-- END BODY -->
</html>