{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%}
{%if $isMobile%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/mdetail.css" />
{%else%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/detail.css" />
{%/if%} 
 <style type="text/css" media="screen">
  
 </style>
 
 
 
{%/block%} 
{%block name="content"%} 
<div class="container main-wrap content-wrap{%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}"> 
 {%if isset($post.id)%}  
    {%if $isapp eq 0%}  
      <div class="bg-img" id="bg-img" style="background-image:url('{%$feroot%}/common/img/imgloading.png'); "  data-stroot="{%$stroot%}"  data-image="{%if empty($post.image)==0%}{%$post.image%}{%/if%}">
      {%if empty($tagName) eq 0 and $isMobile%}
       <div class="back_mask"></div>
         <div class="back clearfix {%if $isMobile%}ismobile{%/if%}">  
            <a href="{%$href%}" class="link">
              <span class="icon"></span>
             <span class="text">{%$tagName%}</span>
            </a> 
         </div>
      {%/if%} 
      <div class="title-box {%if $isMobile%}ismobile{%/if%}">
          <span class="tag">
            {%$post.sight%}
             {%foreach $post.tags as $key=>$item%} 
             · {%$item%}
             {%/foreach%}  
            
          </span>
          <div class="title">
            {%if empty($post.title)==0%}{%$post.title%}{%/if%} 
          </div>
          <div class="like clearfix" style="">
             <i class="collect"></i><span class="number">{%$post.collect%}</span>
             <i class="eye"></i><span class="number">{%$post.visit%}</span>
          </div>
       </div> 
      <div class="img-mask"></div> 
    </div> 
   {%/if%}

  <div class="main-content"> 
    <div class="main-content-inner rich-text{%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}"> 

       {%if empty($post.title)==0%}{%$post.content%}{%/if%}
    </div>
    <div class="text-from{%if $isapp eq 1%} isapp{%/if%} {%if $isMobile%} ismobile{%/if%}">
       {%if empty($post.from_detail) eq 0%}
            内容来自{%$post.from%}
       {%elseif empty($post.from) eq 0%}
            <a href="{%$post.url%}" target="_blank">内容来自{%$post.from%}，查看原网页</a>
       {%/if%} 
    </div>
  </div>
{%/if%}  
</div>
{%if $isapp eq 0%}   
    {%if $isMobile%}{%else%}{%/if%} 
    <div class="header-for-mobile {%if $isMobile%}fixed{%/if%}">
      <a href="/download" class="header-for-mobile-download-link">
      <span class="header-for-mobile-btn">下载iOS版</span>
      <img class="header-for-mobile-logo-img" src="{%$feroot%}/common/img/app-logo.png">
      <span class="header-for-mobile-title">途知</span>
      <span class="header-for-mobile-meta"> 
        了解景点背后的故事 
      </span>
      </a>
    </div>
    {%if $isMobile%}<div class="fixed fixed_blur"></div> {%/if%}
     
{%/if%}  

{%/block%}
{%block name="script"%}
<script> 
    require(['topic/detail'], function (main) {
        main.init();
    }); 
</script>
{%/block%}
