{%extends file="../../../views/common/page.phtml"%}
{%block name="link"%}
{%if $isMobile%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/mdetail.css" />
{%else%}
<link rel="stylesheet" type="text/css" href="{%$feroot%}/topic/css/detail.css" />
{%/if%} 
 
{%/block%} 
{%block name="content"%}
<div class="container main-wrap"> 
 <!--  <div class="top-bar"></div> -->
 {%if isset($post.id)%} 
  <!--  <div class="bg-img"> -->
   <!--  {%if empty($post.image)%} 
   <img src="{%$feroot%}/common/img/imgloading.gif" alt="" class="topic-bg"> 
   {%else%}
   <img src="{%$feroot%}/common/img/imgloading.gif" data-webroot="{%$webroot%}" data-img_hash="{%$post.img_hash%}" data-img_type="{%$post.img_type%}" alt="" class="topic-bg" id="topic-bg">
   {%/if%}   -->
    {%if empty($post.image)%} 
      <div class="bg-img"  style="background-image:url('{%$feroot%}/common/img/imgloading.gif');"> 
    {%else%} 
      <div class="bg-img" id="bg-img" style="background-image:url('{%$feroot%}/common/img/imgloading.gif'); " data-webroot="{%$webroot%}" data-image="{%$post.image%}"> 
    {%/if%}  
    <div class="title-box">
        <div class="title">
          {%if empty($post.title) eq 0%}{%$post.title%}{%/if%} 
        </div>
        <div class="like">
           <i class="fa"></i>{%$post.collect%}
           <i class="fa fa-eye"></i>{%$post.collect%}
        </div>
    </div>
  </div>
  <div class="main-content">
    <div class="main-content-inner rich-text">
       {%if empty($post.content) eq 0%}{%$post.content%}{%/if%}
    </div>
    <div class="text-from">
       {%if empty($post.from_detail) eq 0%}
            来自：{%$post.from%}
       {%elseif empty($post.from) eq 0%}
            来自:{%$post.from%}&nbsp;&nbsp;<a href="{%$post.url%}" target="_blank">查看原网页</a>
       {%/if%} 
    </div>
  </div>
{%/if%}  
</div>
 

{%/block%}
{%block name="script"%}
<script> 
    require(['topic/detail'], function (main) {
        main.init();
    }); 
</script>
{%/block%}