<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>途知</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="{%$feroot%}s/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE STYLES -->
<link href="{%$feroot%}s/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE STYLES -->
<!-- BEGIN THEME STYLES -->
<!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
<link href="{%$feroot%}s/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>   
<!-- <link href="{%$feroot%}s/global/css/bootstrap-reset.css" id="style_components" rel="stylesheet" type="text/css"/>   -->

<link href="{%$feroot%}s/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/global/plugins/bootstrap-toastr/toastr.min.css" rel="stylesheet" type="text/css"/> 
<link href="{%$feroot%}s/admin/layout3/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="{%$feroot%}s/admin/layout3/css/style-responsive.css" rel="stylesheet" type="text/css"/>
 {%block name='link'%}{%/block%}
<!-- END THEME STYLES -->
<script src="{%$feroot%}s/global/plugins/jquery.min.js" type="text/javascript"></script>
<link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body> 
<section id="container"> 
    <!--header start-->
    <header class="header blank-bg">
        <div class="sidebar-toggle-box">
              <div class="fa fa-bars tooltips"></div>
        </div>
        <!--logo start-->
        <a href="/admin" class="logo">Flat<span>途知</span></a>
        <!--logo end--> 
        <div class="top-nav ">
              <ul class="nav pull-right top-menu">
                  <li id="smalltime">--:--:--</li> 
                  <!-- user login dropdown start-->
                  <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <img alt="" src="{%$feroot%}s/global/img/avatar1_small.jpg">
                          <span class="username">{%$username%}</span>
                          <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu extended logout">
                          <div class="log-arrow-up"></div>
                           <li><a href="#"><i class="fa fa-cog"></i>设置</a></li> 
                           <li><a href="#" data-toggle="modal"  data-target="#pwdModal"><i class="fa fa-key"></i>修改密码</a></li> 
                           <li><a href="{%$webroot%}/admin/adminuserapi/logout"><i class="fa fa-sign-out"></i>退出</a></li>
                      </ul>
                  </li>
                  <!-- user login dropdown end --> 
              </ul>
          </div>
    </header> 
    <!--header end -->
    <!--sidebar start-->
    
    	{%include file='common/sidebar3.phtml'%}
    
    <!--main content start-->
    <section id="main-content">
    	<section class="wrapper full-height-content">
          {%include file='utils/changepwd.phtml'%}
    		  {%block name='content'%}{%/block%}
    	</section>
    </section>
    <!--main content end-->
    <!--footer start-->
    <footer class="site-footer">
	    <div class="text-center">
	         2014-2015 © 北京百年兴教网络技术有限公司 
	    </div>
	    <div class="scroll-to-top">
            <i class="fa fa-arrow-circle-o-up"></i>
        </div>
    </footer>
    <!--footer end--> 
</section>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{%$feroot%}s/global/plugins/respond.min.js"></script>
<script src="{%$feroot%}s/global/plugins/excanvas.min.js"></script> 
<![endif]-->

<script src="{%$feroot%}s/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{%$feroot%}s/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-nicescroll/jquery.nicescroll.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.dcjqaccordion.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.scrollTo.min.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script> 
<!-- END CORE PLUGINS -->
 
<script src="{%$feroot%}s/global/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<script src="{%$feroot%}s/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/plugins/bootstrap-toastr/toastr.min.js" type="text/javascript"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{%$feroot%}s/global/scripts/metronic.js" type="text/javascript"></script>
<script src="{%$feroot%}s/global/scripts/json2.js" type="text/javascript"></script> 
<script src="{%$feroot%}s/global/scripts/emitter.js" type="text/javascript"></script>  
<script src="{%$feroot%}s/global/scripts/Remoter.js" type="text/javascript"></script>


<script src="{%$feroot%}s/admin/layout3/js/layout.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/common.js" type="text/javascript"></script>
<!-- <script src="{%$feroot%}s/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script> -->
<!-- <script src="{%$feroot%}s/admin/layout/scripts/demo.js" type="text/javascript"></script> -->
<!-- <script src="{%$feroot%}s/admin/pages/scripts/index.js" type="text/javascript"></script>
<script src="{%$feroot%}s/admin/pages/scripts/tasks.js" type="text/javascript"></script>
 -->
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {    
   Metronic.init(); // init metronic core componets
   Layout.init(); // init layout
   Common.init();//通用
   //QuickSidebar.init(); // init quick sidebar
   //Demo.init(); // init demo features 
/*   Index.init();   
   Index.initDashboardDaterange();
   Index.initJQVMAP(); // init index page's custom scripts
   Index.initCalendar(); // init index page's custom scripts
   Index.initCharts(); // init index page's custom scripts
   Index.initChat();
   Index.initMiniCharts();
   Tasks.initDashboardWidget();*/
});
</script>
{%block name='script'%}{%/block%}
<!-- END JAVASCRIPTS -->
{%block name='modal'%}{%/block%}
</body>

<!-- END BODY -->
</html>
